[QDatepicker] add mobile support
Qvant-lab/qui-max pull request #139
Opened 2021-07-19 13:08 UTC by Tim152

2021-07-19 14:00 UTC, ViZhe requested changes

2021-07-19 14:28 UTC, ViZhe commented on src/qComponents/QDialog/src/QDialog.vue
> +        if (!props.preventFocusAfterClosing) {
это условие скорее должно быть выше и оборачивать вот это https://github.com/Qvant-lab/qui-max/pull/139/files#diff-cce4f8be016b6dfc8ffc5395929304bf2e6ce8d9d0dff86fb0815f3a91740421R244-R246

2021-07-20 07:32 UTC, Tim152 commented on src/qComponents/QDatePicker/src/QDatePicker.vue
> +    });
не вижу смысла тащить зависимость из=за слушателя

2021-07-20 07:32 UTC, Tim152 commented on src/qComponents/QDatePicker/src/QDatePicker.vue
> +      () => dynamicClientWidth.value < 768
?

2021-07-21 16:30 UTC, ViZhe requested changes

2021-07-21 16:30 UTC, ViZhe commented on src/qComponents/QDatePicker/src/QDatePicker.vue
> +          class="q-picker-panel_dialog-view"
скорее элемент `q-picker-panel__dialog-view`

2021-07-21 16:30 UTC, ViZhe commented on src/qComponents/QDatePicker/src/QDatePicker.vue
> +      if (isMobileView.value)
вот тут вероятно нужно разделять конкретно на тач/не тач, ибо нужно показывать контрол очистки ток если у нас нет ховера

2021-07-21 16:30 UTC, ViZhe commented on src/qComponents/QDatePicker/src/panel/q-picker-panel.scss
> +  border-radius: 4px;
`border-radius: var(--border-radius-base);`
и везде где 4px

2021-07-21 16:30 UTC, ViZhe commented on src/qComponents/QDatePicker/src/q-date-picker.scss
> +            font-family: 'qicon';
эт зачем? вроде там и так должно семейство задаваться в самом q-icon

2021-07-29 09:46 UTC, ViZhe requested changes

2021-07-29 09:46 UTC, ViZhe commented on src/qComponents/hooks/index.ts
> +import { useMediaQuery } from './useMediaQuery';
`export { useMediaQuery } from './useMediaQuery';`
или
`export * from './useMediaQuery';`

2021-09-14 15:41 UTC, ViZhe approved these changes

2021-09-16 15:09 UTC, ViZhe commented on src/qComponents/QDatePicker/src/types.ts
> +  reference: Ref<Nullable<UnwrappedInstance<QInputInstance>>>;
UnwrappedInstance уже содержит Nullable 
<img width="433" alt="изображение" src="https://user-images.githubusercontent.com/8091902/133637554-445c1aef-304e-4eba-ba8f-416192bc34e7.png">

2021-09-16 15:12 UTC, ViZhe commented on src/qComponents/QDatePicker/src/types.ts
> +  handleKeydown: (e: KeyboardEvent) => void;
handleKeyDown

2021-09-16 16:01 UTC, ViZhe approved these changes

2021-09-16 16:02 UTC, ViZhe approved these changes

2021-09-17 09:22 UTC, merged