feat: rewrite QDrawer as a plugin
Qvant-lab/qui-max pull request #161
Opened 2021-09-14 08:09 UTC by supra-modum

2021-09-15 09:54 UTC, ViZhe requested changes

2021-09-15 09:54 UTC, ViZhe commented on src/qComponents/QDrawer/index.ts
> +import QDrawer from './src/QDrawerContainer/QDrawer.vue';
экспорт как в МБ

2021-09-15 09:54 UTC, ViZhe commented on src/qComponents/QDrawer/index.ts
> +import { DrawerPlugin, QDrawerHookOptions } from './src/types';
`import type` когда импортируются типы

2021-09-15 09:54 UTC, ViZhe commented on src/qComponents/QDrawer/src/QDrawerContainer/QDrawer.vue
> +    const instance = getCurrentInstance();
первой строчкой в сетапе

2021-09-15 09:54 UTC, ViZhe commented on src/qComponents/QDrawer/src/QDrawerContent/index.ts
> +};
это лишнее

2021-09-15 09:54 UTC, ViZhe commented on src/qComponents/QDrawer/src/QDrawerContainer/QDrawer.vue
> +              @done="doneConfirm"
название `doneConfirm` не соответствует тому что делает функция)

2021-09-15 09:54 UTC, ViZhe commented on src/qComponents/QDrawer/src/QDrawerContainer/QDrawer.vue
> +} from '../types';
типы конкретно этого компонента стоит писать ближе, тобишь на том же уровне вложенности

2021-09-15 09:54 UTC, ViZhe commented on src/qComponents/QDrawer/src/QDrawerContainer/QDrawer.vue
> +    content: {
первым в список пропсов

2021-09-15 09:54 UTC, ViZhe commented on src/qComponents/QDrawer/src/QDrawerContainer/QDrawer.vue
> +      type: [Object, Function] as PropType<Component>,
тип не предусматривает возможность передать компонент с пропасами и слушателями

2021-09-15 09:54 UTC, ViZhe commented on src/qComponents/QDrawer/src/QDrawerContainer/QDrawer.vue
> +    'update:visible',
вероятно лишнее

2021-09-15 09:54 UTC, ViZhe commented on src/qComponents/QDrawer/src/QDrawerContainer/QDrawer.vue
> +  setup(props: QDrawerContainerProps, ctx): QDrawerInstance {
перенос строки

2021-09-15 09:54 UTC, ViZhe commented on src/qComponents/QDrawer/src/QDrawerContainer/QDrawer.vue
>        ctx.emit('update:visible', false);
нужно больше эммитов)

2021-09-15 09:54 UTC, ViZhe commented on src/qComponents/QDrawer/src/QDrawerContainer/QDrawer.vue
> +      () => isVisible,
воч стоит разбить на более подходящие логики, так как у нас появились жизненные циклы компонента

2021-09-15 09:54 UTC, ViZhe commented on src/qComponents/QDrawer/src/QDrawerContainer/q-drawer-container.scss
> +.q-drawer {
стоит поддерживать консистентность между классом и названием компонента

2021-09-15 09:54 UTC, ViZhe commented on src/qComponents/QDrawer/src/QDrawerContent/src/QDrawerContent.vue
> +<template>
этому компоненту не место в src

2021-09-15 09:54 UTC, ViZhe commented on src/qComponents/QDrawer/src/index.ts
> +} from '@/qComponents/QDrawer/src/types';
относительный путь

2021-09-15 09:54 UTC, ViZhe commented on src/qComponents/QDrawer/src/index.ts
> +import { QDrawer } from '@/qComponents/QDrawer';
относительный путь

2021-09-15 09:54 UTC, ViZhe commented on src/qComponents/QDrawer/src/index.ts
> +      return action === QDrawerAction.done
confirm
cancel
close

2021-09-15 09:54 UTC, ViZhe commented on src/qComponents/QDrawer/src/index.ts
> +
перенос лишний

2021-09-15 09:54 UTC, ViZhe commented on src/qComponents/QDrawer/src/index.ts
> +    nextTick(() => {
предотвратить исполнение при SSR

2021-09-15 09:54 UTC, ViZhe commented on src/qComponents/QDrawer/src/index.ts
> +        onClosed: handleClose
onRemove

2021-09-15 09:54 UTC, ViZhe commented on src/qComponents/QDrawer/src/types.ts
> +  // renderOnMount: Nullable<boolean>;
стоит удалить если не нужно больше

2021-09-15 09:54 UTC, ViZhe commented on src/qComponents/QDrawer/src/types.ts
> +export interface QDrawerContainerProps extends QDrawerProps {
QDrawerOptions

2021-09-15 09:54 UTC, ViZhe commented on stories/plugins/QDrawerPlugin/Component.stories.ts
> +// };
стоит использовать

2021-09-15 09:54 UTC, ViZhe commented on stories/plugins/QDrawerPlugin/Component.stories.ts
> +          );
плюс вариант с возможность прокидывать в компонент пропсы и слушатели

2021-09-15 09:54 UTC, ViZhe commented on stories/plugins/QDrawerPlugin/Component.stories.ts
> +      };
слушатели не работают)

2021-09-15 09:54 UTC, ViZhe commented on stories/plugins/QDrawerPlugin/Component.stories.ts
> +import { QDrawer, useDrawer } from '@/qComponents/QDrawer/index';
index лишнее

2021-09-15 09:54 UTC, ViZhe commented on stories/plugins/QDrawerPlugin/Component.stories.ts
> +  title: 'Plugins/QDrawerPlugin/Default',
QDrawerPlugin -> QDrawer

2021-09-15 11:40 UTC, supra-modum commented on src/qComponents/QDrawer/src/QDrawerContainer/QDrawer.vue
> +    content: {
перенесла

2021-09-15 11:41 UTC, supra-modum commented on src/qComponents/QDrawer/src/QDrawerContainer/QDrawer.vue
> +      type: [Object, Function] as PropType<Component>,
передала `QDrawerContainerPropContent` вместо `Component`

2021-09-15 12:19 UTC, supra-modum commented on src/qComponents/QDrawer/src/QDrawerContainer/QDrawer.vue
> +              @done="doneConfirm"
переименовала

2021-09-15 14:08 UTC, supra-modum commented on src/qComponents/QDrawer/src/QDrawerContainer/QDrawer.vue
> +    const instance = getCurrentInstance();
перенесла

2021-09-16 10:50 UTC, supra-modum commented on src/qComponents/QDrawer/index.ts
> +import QDrawer from './src/QDrawerContainer/QDrawer.vue';
исправила

2021-09-16 10:51 UTC, supra-modum commented on src/qComponents/QDrawer/src/QDrawerContent/index.ts
> +};
удалила

2021-09-16 10:51 UTC, supra-modum commented on src/qComponents/QDrawer/src/QDrawerContainer/QDrawer.vue
> +} from '../types';
разделила типы

2021-09-16 10:52 UTC, supra-modum commented on src/qComponents/QDrawer/src/QDrawerContent/src/QDrawerContent.vue
> +<template>
перенесла в сторис

2021-09-16 10:52 UTC, supra-modum commented on src/qComponents/QDrawer/src/index.ts
> +    nextTick(() => {
добавила

2021-09-16 12:16 UTC, supra-modum commented on src/qComponents/QDrawer/src/index.ts
> +        onClosed: handleClose
изменила

2021-09-16 12:17 UTC, supra-modum commented on stories/plugins/QDrawerPlugin/Component.stories.ts
> +import { QDrawer, useDrawer } from '@/qComponents/QDrawer/index';
исправила импорт

2021-09-16 12:18 UTC, supra-modum commented on stories/plugins/QDrawerPlugin/Component.stories.ts
> +  title: 'Plugins/QDrawerPlugin/Default',
переименовала

2021-09-16 12:21 UTC, supra-modum commented on src/qComponents/QDrawer/src/index.ts
> +} from '@/qComponents/QDrawer/src/types';
исправила

2021-09-16 12:22 UTC, supra-modum commented on src/qComponents/QDrawer/src/index.ts
> +import { QDrawer } from '@/qComponents/QDrawer';
исправила

2021-09-16 12:22 UTC, supra-modum commented on stories/plugins/QDrawerPlugin/Component.stories.ts
> +// };
перенесла в дефолтый стори-компонент

2021-09-16 13:14 UTC, ViZhe requested changes

2021-09-16 13:14 UTC, ViZhe commented on stories/plugins/QDrawer/Component.stories.ts
> +      const drawerPlugin = useDrawer();
`drawerPlugin` -> `drawer`

2021-09-16 13:14 UTC, ViZhe commented on stories/plugins/QDrawer/Default.stories.ts
> +
лишний перенос

2021-09-16 13:14 UTC, ViZhe commented on stories/plugins/QDrawer/Default.stories.ts
> +    visible: { control: { type: 'none' } },
это больше не используется насколько я понимаю

2021-09-16 14:25 UTC, supra-modum commented on src/qComponents/QDrawer/src/QDrawerContainer/types.ts
> +    | string;
это лишнее, я забыла удалить. спасибо)

2021-09-17 13:48 UTC, ViZhe requested changes

2021-09-17 13:48 UTC, ViZhe commented on src/qComponents/QDrawerBox/src/QDrawerContainer/index.ts
> +import QDrawerBoxContainer from './index.vue';
Box лишнее)

2021-09-17 13:48 UTC, ViZhe commented on src/qComponents/QDrawerBox/src/QDrawerContainer/index.vue
> +              <slot />
как можно прокинуть слот сюда?

2021-09-17 13:48 UTC, ViZhe commented on src/qComponents/QDrawerBox/src/QDrawerContainer/types.ts
> +  | QDrawerBoxParams
это не контент

2021-09-17 13:48 UTC, ViZhe commented on stories/plugins/QDrawerBox/Component.stories.ts
> +            { width: 350, position: 'right', title: 'What is Lorem Ipsum?' }
хотелось бы определять это динамически через сторибучный интерфейс

2021-09-17 13:48 UTC, ViZhe commented on stories/plugins/QDrawerBox/Extended.stories.ts
> +    visible: { control: { type: 'none' } },
это лишнее

2021-09-17 13:48 UTC, ViZhe commented on stories/plugins/QDrawerBox/QDrawerSampleContent.vue
> +import { QDrawerBoxAction } from '@/qComponents/QDrawerBox/src/constants';
это должно быть доступно из @/qComponents

2021-09-17 13:48 UTC, ViZhe commented on stories/plugins/QDrawerBox/QDrawerSampleContent.vue
> +      const isDone = await commitBeforeClose();
нет смысла и там и там это делать

2021-09-17 13:48 UTC, ViZhe commented on stories/plugins/QDrawerBox/QDrawerSampleContent.vue
> +      const isDone = await commitBeforeClose();
добавь loading на кнопку чтобы показать что что-то происходит

2021-09-17 13:48 UTC, ViZhe commented on stories/plugins/QDrawerBox/Extended.stories.ts
> +import { QDrawerBoxContainerProps } from '@/qComponents/QDrawerBox/src/QDrawerContainer';
`@/qComponents`

2021-09-17 13:48 UTC, ViZhe commented on src/qComponents/QDrawerBox/src/types.ts
> +import { Nullable, UnwrappedInstance } from '#/helpers';
перенос строки до/после

2021-09-17 13:48 UTC, ViZhe commented on src/qComponents/QDrawerBox/src/types.ts
> +import { App, ComponentInternalInstance } from 'vue';
import type и ниже везде

2021-09-17 13:48 UTC, ViZhe commented on src/qComponents/QDrawerBox/src/index.ts
> +  Drawer
QDrawer

2021-09-17 13:48 UTC, ViZhe commented on src/qComponents/QDrawerBox/src/index.ts
> +  Drawer
QDrawer

2021-09-17 13:48 UTC, ViZhe commented on src/qComponents/QDrawerBox/src/index.ts
> +  QDrawerBoxPromise,
DrawerPromise

2021-09-17 13:48 UTC, ViZhe commented on src/qComponents/QDrawerBox/src/QDrawerContainer/types.ts
> +  drawerBox: Ref<Nullable<HTMLElement>>;
drawer

2021-09-17 13:48 UTC, ViZhe commented on src/qComponents/QDrawerBox/src/QDrawerContainer/types.ts
> +export interface QDrawerBoxParams {
это лишнее

2021-09-17 13:48 UTC, ViZhe commented on src/qComponents/QDrawerBox/src/QDrawerContainer/index.vue
> +    onUnmounted(() => {
давай тут `onBeforeUnmount` хотя я не помню почему именно он

2021-09-17 13:48 UTC, ViZhe commented on src/qComponents/QDrawerBox/src/QDrawerContainer/index.vue
> +    wrapperClosable: {
closeOnClickShadow

2021-09-17 13:48 UTC, ViZhe commented on src/qComponents/QDrawerBox/src/QDrawerContainer/index.vue
> +    wrapperClosable: {
и реализацию тени бы из МБ взять

2021-09-17 13:48 UTC, ViZhe commented on src/qComponents/QDrawerBox/src/QDrawerContainer/index.vue
> +    'closed',
поудаляй то что не эмитишь

2021-09-17 13:48 UTC, ViZhe commented on src/qComponents/QDrawerBox/src/QDrawerContainer/index.vue
> +  <teleport :to="teleportTo || 'body'">
:disabled="!teleportTo"

2021-09-17 14:36 UTC, supra-modum commented on src/qComponents/QDrawer/src/QDrawerContainer/QDrawer.vue
> +    'update:visible',
лишнее, убрала!

2021-09-17 14:37 UTC, supra-modum commented on src/qComponents/QDrawer/src/index.ts
> +      return action === QDrawerAction.done
изменила все actions

2021-09-17 14:38 UTC, supra-modum commented on src/qComponents/QDrawer/src/QDrawerContainer/QDrawer.vue
>    componentName: 'QDrawer',
переименовала компонент и файл, классы в todo

2021-09-17 14:38 UTC, supra-modum commented on src/qComponents/QDrawer/src/QDrawerContainer/QDrawer.vue
> +    const isRendered = ref<boolean>(false);
лишнее, удалила

2021-09-17 14:42 UTC, supra-modum commented on src/qComponents/QDrawerBox/src/QDrawerContainer/types.ts
> +  drawerBox: Ref<Nullable<HTMLElement>>;
переименовала

2021-09-17 14:43 UTC, supra-modum commented on src/qComponents/QDrawerBox/src/QDrawerContainer/index.vue
> +    onUnmounted(() => {
вернула

2021-09-17 14:44 UTC, supra-modum commented on src/qComponents/QDrawerBox/src/QDrawerContainer/index.vue
> +    'closed',
удалила лишние эмиты

2021-09-17 14:44 UTC, supra-modum commented on src/qComponents/QDrawerBox/src/QDrawerContainer/index.vue
> +  <teleport :to="teleportTo || 'body'">
вернула

2021-09-17 14:48 UTC, supra-modum commented on stories/plugins/QDrawerBox/QDrawerSampleContent.vue
> +      const isDone = await commitBeforeClose();
добавила реф `isLoading`

2021-09-17 14:48 UTC, supra-modum commented on stories/plugins/QDrawerBox/QDrawerSampleContent.vue
> +      const isDone = await commitBeforeClose();
удалила

2021-09-17 14:50 UTC, supra-modum commented on src/qComponents/QDrawerBox/src/QDrawerContainer/index.ts
> +import QDrawerBoxContainer from './index.vue';
переименовала

2021-09-17 14:53 UTC, supra-modum commented on stories/plugins/QDrawer/Default.stories.ts
> +
убрала

2021-09-17 14:57 UTC, supra-modum commented on src/qComponents/index.ts
> -export * from './QDrawer';
вернула экспорт

2021-09-17 15:03 UTC, supra-modum commented on stories/plugins/QDrawerBox/Extended.stories.ts
> +    visible: { control: { type: 'none' } },
удалила

2021-09-17 15:04 UTC, supra-modum commented on src/qComponents/QDrawerBox/src/types.ts
> +import { Nullable, UnwrappedInstance } from '#/helpers';
исправила

2021-09-17 15:04 UTC, supra-modum commented on src/qComponents/QDrawerBox/src/index.ts
> +  Drawer
переименовала

2021-09-17 15:05 UTC, supra-modum commented on src/qComponents/QDrawerBox/src/index.ts
> +  QDrawerBoxPromise,
переименовала

2021-09-20 07:25 UTC, supra-modum commented on src/qComponents/QDrawerBox/src/QDrawerContainer/index.vue
> +    wrapperClosable: {
изменила

2021-09-20 07:40 UTC, supra-modum commented on src/qComponents/QDrawerBox/src/QDrawerContainer/types.ts
> +export interface QDrawerBoxParams {
удалила

2021-09-20 07:47 UTC, supra-modum commented on stories/plugins/QDrawerBox/QDrawerSampleContent.vue
> +import { QDrawerBoxAction } from '@/qComponents/QDrawerBox/src/constants';
исправила

2021-09-20 10:19 UTC, supra-modum commented on src/qComponents/QDrawerBox/src/QDrawerContainer/types.ts
> +  | QDrawerBoxParams
переименовала

2021-09-20 10:20 UTC, supra-modum commented on src/qComponents/QDrawerBox/src/QDrawerContainer/index.vue
> +              <slot />
лишнее, удалила

2021-09-20 10:20 UTC, supra-modum commented on stories/plugins/QDrawer/Default.stories.ts
> +    visible: { control: { type: 'none' } },
удалила

2021-09-20 10:20 UTC, supra-modum commented on stories/plugins/QDrawer/Component.stories.ts
> +      const drawerPlugin = useDrawer();
переименовала

2021-09-20 12:37 UTC, supra-modum commented on src/qComponents/QDrawer/src/QDrawerContainer/q-drawer-container.scss
> +.q-drawer {
классы изменила

2021-09-20 12:38 UTC, supra-modum commented on src/qComponents/QDrawer/src/QDrawerContainer/types.ts
> +  // renderOnMount: Nullable<boolean>;
удалила

2021-09-20 12:39 UTC, supra-modum commented on src/qComponents/QDrawer/src/QDrawerContainer/QDrawer.vue
>    componentName: 'QDrawer',
классы переименовала

2021-09-20 12:40 UTC, supra-modum commented on src/qComponents/QDrawer/src/QDrawerContainer/QDrawer.vue
> +      () => isVisible,
вотч разбила

2021-09-20 12:44 UTC, supra-modum commented on src/qComponents/QDrawer/src/QDrawerContainer/QDrawer.vue
> +      () => isVisible,
разбила

2021-09-20 12:46 UTC, supra-modum commented on src/qComponents/QDrawer/src/QDrawerContainer/types.ts
> +import type { QDrawerParams } from '../QDrawerContent/types';
лишний нтерфейс, удалила

2021-09-20 12:46 UTC, supra-modum commented on src/qComponents/QDrawerBox/src/index.ts
> +  Drawer
переименовала

2021-09-20 13:06 UTC, ViZhe requested changes

2021-09-21 11:48 UTC, supra-modum commented on stories/plugins/QDrawerBox/Component.stories.ts
> +            { width: 350, position: 'right', title: 'What is Lorem Ipsum?' }
перевела на сторибучные пропсы

2021-09-21 12:01 UTC, supra-modum commented on stories/plugins/QDrawer/Component.stories.ts
> +import type { QDrawerContainerProps } from '@/qComponents/QDrawer/src/QDrawerContainer';
исправила

2021-09-21 12:06 UTC, supra-modum commented on stories/plugins/QDrawer/Extended.stories.ts
> +            { title: args.title, width: args.width, position: args.position }
добавила

2021-09-21 12:07 UTC, supra-modum commented on stories/plugins/QDrawer/QDrawerSampleContent.vue
> +import { QForm, QFormItem, QInput, QButton } from '@/qComponents';
добавила

2021-09-21 12:08 UTC, supra-modum commented on stories/plugins/QDrawer/QDrawerSampleContent.vue
> +      console.log(action);
удалила

2021-09-21 12:08 UTC, supra-modum commented on stories/plugins/QDrawer/QDrawerSampleContent.vue
> +      console.log(action);
удалила

2021-09-21 12:10 UTC, supra-modum commented on src/qComponents/QDrawer/src/QDrawerContainer/index.vue
> +      document.removeEventListener('focus', handleDocumentFocus, true);
удалила

2021-09-21 12:11 UTC, supra-modum commented on src/qComponents/QDrawer/src/QDrawerContainer/index.vue
> +      elementToFocusAfterClosing?.focus();
перенесла

2021-09-21 13:07 UTC, supra-modum commented on src/qComponents/QDrawer/index.ts
> +  QDrawerContainerProps,
вынесла экспорт

2021-09-21 13:09 UTC, supra-modum commented on stories/plugins/QDrawerBox/Extended.stories.ts
> +import { QDrawerBoxContainerProps } from '@/qComponents/QDrawerBox/src/QDrawerContainer';
поменяла импорт

2021-09-21 13:13 UTC, supra-modum commented on src/qComponents/QDrawer/src/types.ts
> +} from './QDrawerContainer/types';
исправила экспорт

2021-09-21 13:38 UTC, supra-modum commented on src/qComponents/QDrawerBox/src/types.ts
> +import { App, ComponentInternalInstance } from 'vue';
исправила

2021-09-21 14:43 UTC, supra-modum commented on src/qComponents/QDrawer/src/QDrawerContainer/index.vue
> +      if (props.closeOnClickShadow) closeBox({ action: QDrawerAction.close });
close/cancel разделила

2021-09-21 15:29 UTC, Tim152 commented on stories/plugins/QDrawer/Component.stories.ts
> +import type { QDrawerContainerProps } from '@/qComponents/QDrawer/';
лишний слеш в конце

2021-09-21 15:34 UTC, supra-modum commented on stories/plugins/QDrawer/Component.stories.ts
> +import type { QDrawerContainerProps } from '@/qComponents/QDrawer/';
исправила

2021-09-21 15:38 UTC, ViZhe requested changes

2021-09-21 15:38 UTC, ViZhe commented on src/qComponents/QDrawer/src/QDrawerContent/index.vue
> +    <div class="q-drawer-content__content">
q-drawer-content__body

2021-09-21 15:38 UTC, ViZhe commented on src/qComponents/QDrawer/src/QDrawerContent/index.vue
> +      <slot name="content" />
дефотлный слот

2021-09-21 15:38 UTC, ViZhe commented on src/qComponents/QDrawer/src/QDrawerContainer/utils.ts
> +export const isInternalComponent = (
лишнее

2021-09-21 15:38 UTC, ViZhe commented on src/qComponents/QDrawer/src/QDrawerContainer/index.vue
> +      }
лишнее

2021-09-21 15:38 UTC, ViZhe commented on stories/plugins/QDrawer/QDrawerSampleContent.vue
> +import { QForm, QFormItem, QInput, QButton } from '@/qComponents';
добавь QDrawerContent, QDrawerAction сюда, а то что ниже дропни

2021-09-21 15:38 UTC, ViZhe commented on stories/plugins/QDrawer/Extended.stories.ts
> +
лишний перенос

2021-09-21 15:38 UTC, ViZhe commented on src/qComponents/QDrawer/src/QDrawerContainer/types.ts
> +export interface QDrawerContainerProps extends QDrawerOptions {
избавься от extends QDrawerOptions
продублируй сюда те свойства что тут реально нужны

2021-09-21 15:38 UTC, ViZhe commented on src/qComponents/QDrawer/src/QDrawerContainer/types.ts
> +  props?: QDrawerOptions | { [propName: string]: unknown };
QDrawerOptions лишнее

2021-09-21 15:38 UTC, ViZhe commented on src/qComponents/QDrawer/src/QDrawerContainer/types.ts
> +  | QDrawerOptions
лишнее

2021-09-21 15:38 UTC, ViZhe commented on src/qComponents/QDrawer/src/QDrawerContainer/index.vue
> +            </div>
это лишнее так как заголовок теперь в  контенте
соответственно как и пропс

2021-09-21 15:38 UTC, ViZhe commented on src/qComponents/QDrawer/src/QDrawerContainer/index.ts
> +  QDrawerPropTeleportTo
из QDrawerContainer должны ток QDrawerContainer экспортиться

2021-09-21 16:06 UTC, supra-modum commented on src/qComponents/QDrawer/src/QDrawerContainer/utils.ts
> +export const isInternalComponent = (
удалила

2021-09-21 16:06 UTC, supra-modum commented on src/qComponents/QDrawer/src/QDrawerContainer/types.ts
> +export interface QDrawerContainerProps extends QDrawerOptions {
удалила, свойства перенесла

2021-09-21 16:06 UTC, supra-modum commented on src/qComponents/QDrawer/src/QDrawerContainer/types.ts
> +  props?: QDrawerOptions | { [propName: string]: unknown };
удалила

2021-09-21 16:06 UTC, supra-modum commented on src/qComponents/QDrawer/src/QDrawerContainer/index.vue
> +            </div>
удалила

2021-09-21 16:06 UTC, supra-modum commented on src/qComponents/QDrawer/src/QDrawerContainer/index.ts
> +  QDrawerPropTeleportTo
переименовала

2021-09-21 16:15 UTC, supra-modum commented on src/qComponents/QDrawer/src/QDrawerContent/index.vue
> +    <div class="q-drawer-content__content">
переименовала

2021-09-21 16:23 UTC, supra-modum commented on src/qComponents/QDrawer/src/QDrawerContent/index.vue
> +      <slot name="content" />
поставила default

2021-09-21 16:23 UTC, supra-modum commented on stories/plugins/QDrawer/Extended.stories.ts
> +
удалила

2021-09-21 16:26 UTC, supra-modum commented on stories/plugins/QDrawer/QDrawerSampleContent.vue
> +import { QForm, QFormItem, QInput, QButton } from '@/qComponents';
перенесла

2021-09-21 16:54 UTC, ViZhe requested changes

2021-09-21 16:54 UTC, ViZhe commented on src/qComponents/QDrawer/src/QDrawerContainer/index.ts
> +  QDrawerContainerPropTeleportTo
лучше их размещать в порядке определения

  QDrawerContainerPropContent,
  QDrawerContainerPropPosition,
  QDrawerContainerPropTeleportTo
  QDrawerContainerProps,
  QDrawerContainerInstance,

2021-09-21 16:54 UTC, ViZhe commented on src/qComponents/QDrawer/src/QDrawerContainer/index.vue
> +  QDrawerContainerPropTeleportTo
тут тоже в порядке объявления

2021-09-21 16:54 UTC, ViZhe commented on src/qComponents/QDrawer/src/QDrawerContainer/q-drawer-container.scss
> +  }
этого уже нет в контейнере

2021-09-21 16:54 UTC, ViZhe commented on src/qComponents/QDrawer/src/QDrawerContainer/types.ts
> +  distinguishCancelAndClose?: Nullable<boolean>;
лучше в порядке как в props компонента

2021-09-21 16:54 UTC, ViZhe commented on src/qComponents/QDrawer/src/QDrawerContainer/index.vue
> +          </q-scrollbar>
нужно чтобы тело скролилось, а шапка (крестик + тайтл) нет
плюс давай перенесём крестик тоже в qdrawercontent

2021-09-21 16:54 UTC, ViZhe commented on src/qComponents/QDrawer/src/QDrawerContainer/q-drawer-container.scss
> +    &:focus,
лишнее

2021-09-21 16:54 UTC, ViZhe commented on src/qComponents/QDrawer/src/QDrawerContainer/q-drawer-container.scss
> +    &:focus-visible {
&.focus-visible

2021-09-21 16:54 UTC, ViZhe commented on src/qComponents/QDrawer/src/types.ts
> +  parentInstance?: Nullable<ComponentInternalInstance>;
это перед onBeforeMount

2021-09-21 16:54 UTC, ViZhe commented on src/qComponents/QDrawer/src/QDrawerContainer/types.ts
> +  parentInstance?: Nullable<ComponentInternalInstance>;
такого пропса нет у контейнера

2021-09-21 16:54 UTC, ViZhe commented on src/qComponents/QDrawer/src/types.ts
> +  teleportTo?: QDrawerContainerPropTeleportTo;
в порядке как в дроветконтейнере

2021-09-21 16:54 UTC, ViZhe commented on stories/plugins/QDrawer/Component.stories.ts
> +import { useDrawer } from '@/qComponents/QDrawer';
import { useDrawer } from '@/qComponents';

2021-09-21 16:54 UTC, ViZhe commented on stories/plugins/QDrawer/Component.stories.ts
> +import type { QDrawerContainerProps } from '@/qComponents/QDrawer';
import type { QDrawerOptions } from '@/qComponents';

2021-09-21 16:54 UTC, ViZhe commented on stories/plugins/QDrawer/Component.stories.ts
> +const QDrawerStoryComponent: Story<QDrawerContainerProps> = args =>
const QDrawerStoryComponent: Story<QDrawerOptions> = args =>

2021-09-21 16:54 UTC, ViZhe commented on stories/plugins/QDrawer/Component.stories.ts
> +  position: 'right',
это дефолт - можно дропнуть

2021-09-21 16:54 UTC, ViZhe commented on stories/plugins/QDrawer/Component.stories.ts
> +  distinguishCancelAndClose: true
это я б тоже дропнул, не особо показательно для примера

2021-09-21 16:54 UTC, ViZhe commented on stories/plugins/QDrawer/Extended.stories.ts
> +import type { QDrawerContainerProps } from '@/qComponents';
QDrawerOptions

2021-09-21 16:54 UTC, ViZhe commented on stories/plugins/QDrawer/Extended.stories.ts
> +const QDrawerStoryComponent: Story<QDrawerContainerProps> = args =>
QDrawerOptions

2021-09-21 16:54 UTC, ViZhe commented on stories/plugins/QDrawer/Extended.stories.ts
> +  distinguishCancelAndClose: true
тоже самое и position тоже

2021-09-21 16:54 UTC, ViZhe commented on stories/plugins/QDrawer/QDrawerSampleContent.vue
> +    <template #default>
лишнее, дефолт необязательно в темплейт оборачивать

2021-09-21 16:54 UTC, ViZhe commented on stories/plugins/QDrawer/QDrawerSampleContent.vue
> +      <p>Morbi massa libero, vehicula nec consequat sed, porta a sem.</p>
тег лишний

2021-09-22 08:27 UTC, supra-modum commented on stories/plugins/QDrawer/QDrawerSampleContent.vue
> +      <p>Morbi massa libero, vehicula nec consequat sed, porta a sem.</p>
удалила

2021-09-22 08:27 UTC, supra-modum commented on stories/plugins/QDrawer/QDrawerSampleContent.vue
> +    <template #default>
удалила

2021-09-22 08:28 UTC, supra-modum commented on stories/plugins/QDrawer/Extended.stories.ts
> +const QDrawerStoryComponent: Story<QDrawerContainerProps> = args =>
поменяла

2021-09-22 08:30 UTC, supra-modum commented on stories/plugins/QDrawer/Component.stories.ts
> +import type { QDrawerContainerProps } from '@/qComponents/QDrawer';
поправила

2021-09-22 08:30 UTC, supra-modum commented on stories/plugins/QDrawer/Component.stories.ts
> +import { useDrawer } from '@/qComponents/QDrawer';
исправила

2021-09-22 08:31 UTC, supra-modum commented on src/qComponents/QDrawer/src/QDrawerContainer/types.ts
> +  parentInstance?: Nullable<ComponentInternalInstance>;
удалила

2021-09-22 08:32 UTC, supra-modum commented on src/qComponents/QDrawer/src/types.ts
> +  parentInstance?: Nullable<ComponentInternalInstance>;
перенесла

2021-09-22 08:50 UTC, supra-modum commented on src/qComponents/QDrawer/src/QDrawerContainer/q-drawer-container.scss
> +    &:focus,
удалила

2021-09-22 08:50 UTC, supra-modum commented on src/qComponents/QDrawer/src/QDrawerContainer/q-drawer-container.scss
> +    &:focus-visible {
исправила

2021-09-22 08:51 UTC, supra-modum commented on stories/plugins/QDrawer/Component.stories.ts
> +  position: 'right',
удалила

2021-09-22 08:51 UTC, supra-modum commented on stories/plugins/QDrawer/Component.stories.ts
> +  distinguishCancelAndClose: true
удалила

2021-09-22 08:52 UTC, supra-modum commented on stories/plugins/QDrawer/Extended.stories.ts
> +import type { QDrawerContainerProps } from '@/qComponents';
измменила

2021-09-22 08:53 UTC, supra-modum commented on stories/plugins/QDrawer/Extended.stories.ts
> +  distinguishCancelAndClose: true
удалила

2021-09-22 08:55 UTC, supra-modum commented on src/qComponents/QDrawer/src/QDrawerContainer/index.ts
> +  QDrawerContainerPropTeleportTo
исправила

2021-09-22 08:59 UTC, supra-modum commented on src/qComponents/QDrawer/src/QDrawerContainer/index.vue
> +  QDrawerContainerPropTeleportTo
исправила

2021-09-22 09:03 UTC, supra-modum commented on src/qComponents/QDrawer/src/QDrawerContainer/q-drawer-container.scss
> +  }
перенесла в стили контента

2021-09-22 09:55 UTC, supra-modum commented on stories/plugins/QDrawer/Component.stories.ts
> +const QDrawerStoryComponent: Story<QDrawerContainerProps> = args =>
исправила на qdraweroptions

2021-09-23 12:10 UTC, ViZhe requested changes

2021-09-23 12:10 UTC, ViZhe commented on src/qComponents/QDrawer/src/QDrawerContent/index.vue
>    setup() {
типизация инстанса

2021-09-23 12:10 UTC, ViZhe commented on src/qComponents/QDrawer/src/QDrawerContent/index.vue
> +    const handleDrawerCloseButtonClick =
лучше не передавать напрямую, так как там может не быть функции, а сделать метод который вызывает то что прокинуто если оно есть
плюс название скорее `handleCloseBtnClick`

2021-09-23 12:10 UTC, ViZhe commented on src/qComponents/QDrawer/src/QDrawerContent/index.vue
>  import QScrollbar from '@/qComponents/QScrollbar';
перенос строки до и после

2021-09-23 12:10 UTC, ViZhe commented on src/qComponents/QDrawer/src/QDrawerContent/index.vue
> +    <div class="q-drawer-content__header">
думаю от header можно избавиться

2021-09-23 12:10 UTC, ViZhe commented on src/qComponents/QDrawer/src/QDrawerContent/index.vue
> +      visible
вот этот пропс давай дропнем

2021-09-23 12:10 UTC, ViZhe commented on src/qComponents/QDrawer/src/QDrawerContent/index.vue
> +      class="q-drawer-content__scrollbar"
не уверен что это тут нужно

2021-09-23 12:10 UTC, ViZhe commented on src/qComponents/QDrawer/src/QDrawerContent/q-drawer-content.scss
> +    }
кажется центровать в дровере ничего не нужно

2021-09-23 12:10 UTC, ViZhe commented on src/qComponents/QDrawer/src/QDrawerContent/q-drawer-content.scss
> +    }
это скорее всего тоже лишнее

2021-09-23 12:10 UTC, ViZhe commented on src/qComponents/QDrawer/src/QDrawerContent/q-drawer-content.scss
> +      outline: none;
outline тут тоже скорее всего избыточен

2021-09-23 14:06 UTC, supra-modum commented on src/qComponents/QDrawer/src/QDrawerContainer/index.vue
> +    provide<QDrawerContainerProvider>('QDrawerContainer', {
переименовала

2021-09-23 14:07 UTC, supra-modum commented on src/qComponents/QDrawer/src/QDrawerContent/index.vue
> +      visible
удалила

2021-09-23 14:07 UTC, supra-modum commented on src/qComponents/QDrawer/src/QDrawerContent/index.vue
> +      class="q-drawer-content__scrollbar"
удалила

2021-09-23 14:07 UTC, supra-modum commented on src/qComponents/QDrawer/src/QDrawerContent/index.vue
> +      inject<QDrawerContainerProvider>('QDrawerContainer');
изменила

2021-09-23 14:27 UTC, supra-modum commented on src/qComponents/QDrawer/src/QDrawerContent/index.vue
> +    const handleDrawerCloseButtonClick =
переделала

2021-09-23 14:30 UTC, supra-modum commented on src/qComponents/QDrawer/src/QDrawerContent/index.vue
>    setup() {
вернула типы

2021-09-23 14:42 UTC, supra-modum commented on src/qComponents/QDrawer/src/QDrawerContent/index.vue
> +    <div class="q-drawer-content__header">
да, вроде ничего не сломалось. удалила

2021-09-23 15:11 UTC, supra-modum commented on src/qComponents/QDrawer/src/QDrawerContainer/types.ts
> +  distinguishCancelAndClose?: Nullable<boolean>;
поправила

2021-09-23 15:30 UTC, supra-modum commented on src/qComponents/QDrawer/src/QDrawerContent/q-drawer-content.scss
> +    }
удалила

2021-09-23 15:33 UTC, supra-modum commented on src/qComponents/QDrawer/src/types.ts
> +  teleportTo?: QDrawerContainerPropTeleportTo;
поменяла

2021-09-23 15:33 UTC, supra-modum commented on src/qComponents/QDrawer/src/QDrawerContent/q-drawer-content.scss
> +    }
удалила

2021-09-23 15:34 UTC, supra-modum commented on src/qComponents/QDrawer/src/QDrawerContent/q-drawer-content.scss
> +      outline: none;
удалила

2021-09-23 15:35 UTC, supra-modum commented on src/qComponents/QDrawer/src/QDrawerContent/index.vue
>  import QScrollbar from '@/qComponents/QScrollbar';
исправила

2021-09-23 15:40 UTC, supra-modum commented on src/qComponents/QDrawer/src/QDrawerContent/index.vue
> +    <div class="q-drawer-content__header">
Все же ломается кнопка без контейнера, вернула назад

2021-09-23 15:56 UTC, ViZhe requested changes

2021-09-23 15:56 UTC, ViZhe commented on src/qComponents/QDrawer/src/QDrawerContent/index.vue
> +      QDrawerContainer?.closeBox({
QDrawerContainer?.emitCloseEvent()

2021-09-23 15:56 UTC, ViZhe commented on src/qComponents/QDrawer/src/QDrawerContent/index.vue
> +    distinguishCancelAndClose: {
это лишнее

2021-09-23 15:56 UTC, ViZhe commented on src/qComponents/QDrawer/src/QDrawerContent/q-drawer-content.scss
>      justify-content: center;
это лишнее

2021-09-23 15:56 UTC, ViZhe commented on src/qComponents/QDrawer/src/QDrawerContent/index.vue
> +      class="q-drawer-content__scrollbar"
не то удалила) и стили тоже нужно

2021-09-24 09:24 UTC, supra-modum commented on src/qComponents/QDrawer/src/QDrawerContent/index.vue
> +      QDrawerContainer?.closeBox({
исправила

2021-09-24 09:24 UTC, supra-modum commented on src/qComponents/QDrawer/src/QDrawerContent/q-drawer-content.scss
>      justify-content: center;
удалила

2021-09-24 09:24 UTC, supra-modum commented on src/qComponents/QDrawer/src/QDrawerContent/index.vue
> +    distinguishCancelAndClose: {
удалила

2021-09-24 09:25 UTC, supra-modum commented on src/qComponents/QDrawer/src/QDrawerContent/index.vue
> +      class="q-drawer-content__scrollbar"
теперь точно все удалила)

2021-09-24 13:00 UTC, ViZhe requested changes

2021-09-24 13:00 UTC, ViZhe commented on src/qComponents/QDrawer/src/QDrawerContent/index.vue
> +    <div class="q-drawer-content__header">
нужно убрать и сделать так чтобы не ломалось)

2021-09-24 13:00 UTC, ViZhe commented on src/qComponents/QDrawer/index.ts
> +export { QDrawerContent } from './src/QDrawerContent';
так же нужно экспортить QDrawerContentProps и QDrawerContentInstance

2021-09-24 13:00 UTC, ViZhe commented on src/qComponents/QDrawer/src/QDrawerContent/types.ts
> +  distinguishCancelAndClose?: Nullable<boolean>;
это лишнее

2021-09-24 13:00 UTC, ViZhe commented on stories/plugins/QDrawer/Component.stories.ts
> +              distinguishCancelAndClose: true
это нужно там же где width прописывать иначе ломается возможность изменять это
но в целом это лишнее, так как можно в ui сторибука задать если нужно

2021-09-24 13:00 UTC, ViZhe commented on stories/plugins/QDrawer/DrawerFormTest.vue
> +    <div class="q-drawer-content__actions">
q-drawer-sample-content__actions

2021-09-24 13:00 UTC, ViZhe commented on stories/plugins/QDrawer/DrawerFormTest.vue
> +  QButton,
`QForm,  QFormItem,  QInput,  QButton,`
уже вроде как нет необходимости регистрировать эти компоненты

2021-09-24 13:00 UTC, ViZhe commented on stories/plugins/QDrawer/Extended.stories.ts
> +              distinguishCancelAndClose: true
это лишнее

2021-09-27 07:45 UTC, supra-modum commented on src/qComponents/QDrawer/index.ts
> +export { QDrawerContent } from './src/QDrawerContent';
добавила экспорт

2021-09-27 07:45 UTC, supra-modum commented on src/qComponents/QDrawer/src/QDrawerContent/index.vue
> +    <div class="q-drawer-content__header">
убрала

2021-09-27 07:51 UTC, supra-modum commented on src/qComponents/QDrawer/src/QDrawerContent/index.vue
> +import { QDrawerContentInstance, QDrawerContentProps } from './types';
добавила

2021-09-27 07:51 UTC, supra-modum commented on src/qComponents/QDrawer/src/QDrawerContent/types.ts
> +  distinguishCancelAndClose?: Nullable<boolean>;
удалила

2021-09-27 07:53 UTC, supra-modum commented on stories/plugins/QDrawer/Component.stories.ts
> +              distinguishCancelAndClose: true
поправила

2021-09-27 07:54 UTC, supra-modum commented on stories/plugins/QDrawer/DrawerFormTest.vue
> +    <div class="q-drawer-content__actions">
изменила класс

2021-09-27 07:55 UTC, supra-modum commented on stories/plugins/QDrawer/Extended.stories.ts
> +              distinguishCancelAndClose: true
перенесла в сторибучные пропсы

2021-09-27 09:08 UTC, supra-modum commented on stories/plugins/QDrawer/DrawerFormTest.vue
> +  QButton,
удалила

2021-09-27 09:15 UTC, Tim152 commented on src/qComponents/QDrawer/src/QDrawerContainer/q-drawer-container.scss
> +    padding: 24px 0 24px 0;
можно шорткатом
padding: 24px 0;

2021-09-27 09:27 UTC, supra-modum commented on src/qComponents/QDrawer/src/QDrawerContainer/q-drawer-container.scss
> +    padding: 24px 0 24px 0;
пропустила. спасибо, исправила)

2021-09-27 10:07 UTC, ViZhe requested changes

2021-09-27 10:07 UTC, ViZhe commented on src/qComponents/QDrawer/src/QDrawerContainer/q-drawer-container.scss
> +    padding: 24px 0 24px 0;
но тут скорее им не место, я б сказал что это зона ответственности q-drawer-content
и скорее
padding-top:24px;
padding-bottom:24px;

2021-09-27 10:07 UTC, ViZhe commented on src/qComponents/QDrawer/src/QDrawerContent/q-drawer-content.scss
> +  height: 100%;
плюс position: relative

2021-09-27 10:11 UTC, ViZhe commented on src/qComponents/QDrawer/src/QDrawerContainer/q-drawer-container.scss
> +    padding: 24px 0 24px 0;
точнее даже не так, а margin-top: 24px; y .q-drawer-content__title

2021-09-27 10:13 UTC, ViZhe commented on src/qComponents/QDrawer/src/QDrawerContent/q-drawer-content.scss
> +    padding: 0 24px;
margin: 24px 24px 32px;

2021-09-27 10:17 UTC, ViZhe commented on stories/plugins/QDrawer/Extended.stories.ts
> +  distinguishCancelAndClose: true
хм, вроде бы нет, и в первом примере тоже

2021-09-27 11:44 UTC, supra-modum commented on src/qComponents/QDrawer/src/QDrawerContainer/q-drawer-container.scss
> +    padding: 24px 0 24px 0;
удалила отступ сверху и снизу у wrapper, поставила margin для тайтла

2021-09-27 11:46 UTC, supra-modum commented on src/qComponents/QDrawer/src/QDrawerContainer/types.ts
> +  closeOnClickShadow?: Nullable<boolean>;
удалила

2021-09-27 11:48 UTC, supra-modum commented on src/qComponents/QDrawer/src/types.ts
> +  position: QDrawerContainerPropPosition;
добавила

2021-09-27 11:49 UTC, supra-modum commented on stories/plugins/QDrawer/DrawerFormTest.vue
> +    justify-content: flex-start;
удалила

2021-09-27 11:58 UTC, supra-modum commented on stories/plugins/QDrawer/DrawerFormTest.vue
> +      default: null
добавила

2021-09-27 14:01 UTC, supra-modum commented on src/qComponents/QDrawer/src/QDrawerContent/q-drawer-content.scss
> +  height: 100%;
добавила

2021-09-28 08:15 UTC, ViZhe approved these changes

2021-09-28 08:33 UTC, Tim152 approved these changes

2021-09-28 08:34 UTC, merged