[QDialog] Make component usage as a hook
Qvant-lab/qui-max pull request #162
Opened 2021-09-14 08:45 UTC by SeregaBB

2021-09-15 08:59 UTC, ViZhe requested changes

2021-09-15 08:59 UTC, ViZhe commented on src/qComponents/QDialog/index.ts
> +import { createDialog } from '@/qComponents/QDialog/src';
тут лучше относительные пути

2021-09-15 08:59 UTC, ViZhe commented on src/qComponents/QDialog/index.ts
> +export const useDialog = (options?: QDialogHookOptions): Dialog => {
нужно больше консистентности с MB

2021-09-15 08:59 UTC, ViZhe commented on src/qComponents/QDialog/src/QDialogContent/index.ts
> +};
не понятно зачем это

2021-09-15 08:59 UTC, ViZhe commented on src/qComponents/QDialog/src/index.ts
> +      dialogPromise.resolve('closed');
нет возможности вернуть значение из диалога в код

2021-09-15 08:59 UTC, ViZhe commented on src/qComponents/QDialog/src/QDialog.vue
> +      () => isVisible,
от этого вотча нужно отказаться и раскидать функционал по более подходящим местам

2021-09-15 09:08 UTC, ViZhe requested changes

2021-09-15 09:08 UTC, ViZhe commented on stories/components/QDialog.stories.ts
> +            ),
так же нужен вариант с возможностью прокидывать пропсы и слушатели в компонент как в МБ

2021-09-16 09:28 UTC, ViZhe requested changes

2021-09-16 09:28 UTC, ViZhe commented on src/qComponents/QDialog/src/QDialog.vue
> +import { isDialogExternalComponent } from '@/qComponents/QDialog/src/utils';
абсолютные пути стоит использовать только там где без них не обойтись

2021-09-16 09:28 UTC, ViZhe commented on src/qComponents/QDialog/src/QDialog.vue
> +                  v-on="preparedDialogContent.listeners"
preparedContent

2021-09-16 09:28 UTC, ViZhe commented on src/qComponents/QDialog/src/QDialog.vue
> +        v-show="isVisible"
isShown

2021-09-16 09:28 UTC, ViZhe commented on src/qComponents/QDialog/index.ts
> +export const useDialog = (options?: QDialogHookOptions): Dialog => {
ещё больше консистентности

2021-09-16 09:28 UTC, ViZhe commented on src/qComponents/QDialog/src/QDialog.vue
> +    content: {
первым пропсом

2021-09-16 09:28 UTC, ViZhe commented on src/qComponents/QDialog/src/QDialog.vue
>      wrapperClosable: {
closeOnClickShadow

2021-09-16 09:28 UTC, ViZhe commented on src/qComponents/QDialog/src/QDialog.vue
> +    'update:visible',
зачем?

2021-09-16 09:28 UTC, ViZhe commented on src/qComponents/QDialog/src/QDialog.vue
> +  setup(props: QDialogContainerProps, ctx): QDialogInstance {
QDialogContainerProps но QDialogInstance? консистентность
название компонента, его типы и стилевой блок всё это должно говорить о том где мы

2021-09-16 09:28 UTC, ViZhe commented on src/qComponents/QDialog/src/QDialog.vue
> +    const instance = getCurrentInstance();
первой строчкой в сетапе

2021-09-16 09:28 UTC, ViZhe commented on src/qComponents/QDialog/src/QDialog.vue
> +      if (isDialogExternalComponent(props.content)) {
isExternalComponent

2021-09-16 09:28 UTC, ViZhe commented on src/qComponents/QDialog/src/QDialogContent/QdialogContent.vue
> +<template>
что это делает в src?

2021-09-16 09:28 UTC, ViZhe commented on src/qComponents/index.ts
> -export * from './QDialog';
как планируется использовать плагин если он не экспортируется?

2021-09-16 09:28 UTC, ViZhe commented on stories/plugins/QDialog/Extended.stories.ts
> +      };
не используются

2021-09-16 09:28 UTC, ViZhe commented on stories/plugins/QDialog/Extended.stories.ts
> +            },
пример с событиями?

2021-09-16 13:39 UTC, ViZhe requested changes

2021-09-16 13:39 UTC, ViZhe commented on src/qComponents/QDialog/src/QDialogContainer/index.vue
> +    onBeforeUnmount(() => {
почему поменялось?

2021-09-16 13:39 UTC, ViZhe commented on stories/plugins/QDialog/Extended.stories.ts
> +      <q-button @click="openDialog">open</q-button>
handleClick

2021-09-16 13:39 UTC, ViZhe commented on stories/plugins/QDialog/QdialogContent.vue
> +      emit('closed');
?

2021-09-16 13:39 UTC, ViZhe commented on stories/plugins/QDialog/QdialogContent.vue
> +  name: 'QDialogContent',
`DialogFormTest`
и в шаблоне набросать простенькую форму с 2 действиями
cancel
confirm

2021-09-16 13:39 UTC, ViZhe commented on stories/plugins/QDialog/Extended.stories.ts
> +          const res = await dialog(
result

2021-09-16 13:39 UTC, ViZhe commented on stories/plugins/QDialog/Default.stories.ts
> +        args,
где используется?

2021-09-16 13:39 UTC, ViZhe commented on stories/plugins/QDialog/Default.stories.ts
> +import { QDialog, useDialog } from '@/qComponents';
перенос строки перед

2021-09-16 13:39 UTC, ViZhe commented on src/qComponents/QDialog/src/utils.ts
> +import { has } from 'lodash-es';
стоит расположить файл ближе к тому где он используется

2021-09-17 14:25 UTC, ViZhe requested changes

2021-09-17 14:25 UTC, ViZhe commented on src/qComponents/QDialog/src/QDialogContainer/index.vue
>        if (dialog.value && !dialog.value.contains(event.target as HTMLElement)) {
const dialogValue = dialog.value;

2021-09-17 14:25 UTC, ViZhe commented on src/qComponents/QDialog/src/QDialogContainer/index.vue
>      const afterEnter = (): void => {
лишний

2021-09-17 14:25 UTC, ViZhe commented on src/qComponents/QDialog/src/QDialogContainer/index.vue
> +      dialog.value?.focus();
на маунте

2021-09-17 14:25 UTC, ViZhe commented on src/qComponents/QDialog/src/QDialogContainer/index.vue
>        ctx.emit('opened');
пока убей все лишние эмиты

2021-09-17 14:25 UTC, ViZhe commented on src/qComponents/QDialog/src/QDialogContainer/index.vue
> +      document.removeEventListener('focus', handleDocumentFocus, true);
лишнее

2021-09-17 14:25 UTC, ViZhe commented on src/qComponents/QDialog/src/QDialogContainer/index.vue
> +        closeDialog({ action: QDialogAction.close });
пронаследуй реализацию тени и логики по кликам из МБ

2021-09-17 14:25 UTC, ViZhe commented on src/qComponents/QDialog/src/QDialogContainer/index.vue
> +    const zIndex = ref<number>(DEFAULT_Z_INDEX);
const zIndex = getConfig('nextZIndex');

2021-09-17 14:25 UTC, ViZhe commented on src/qComponents/QDialog/src/QDialogContainer/index.vue
> +      zIndex.value = getConfig('nextZIndex') ?? DEFAULT_Z_INDEX;
лишнее

2021-09-17 14:25 UTC, ViZhe commented on src/qComponents/QDialog/src/QDialogContainer/index.vue
> +      isShown.value = true;
await nextTick(); перед этим

2021-09-17 14:25 UTC, ViZhe commented on src/qComponents/QDialog/src/QDialogContainer/index.vue
> +      elementToFocusAfterClosing?.focus();
перенеси в onBeforeUnmount после отписки

2021-09-17 14:25 UTC, ViZhe commented on src/qComponents/QDialog/src/QDialogContainer/index.vue
> +      preparedContent
стоиит соблюдать тут порядок тот же что и в коде, то есть в порядке объявления

2021-09-17 14:25 UTC, ViZhe commented on src/qComponents/QDialog/src/QDialogContainer/types.ts
> +  preparedContent: ComputedRef<QDialogComponent>;
тоже в порядке объявления

2021-09-17 14:25 UTC, ViZhe commented on src/qComponents/QDialog/src/index.ts
> +  return dialog;
перенос перед

2021-09-17 14:25 UTC, ViZhe commented on src/qComponents/QDialog/src/index.ts
> +      if (!app) return;
перенос после

2021-09-17 14:25 UTC, ViZhe commented on src/qComponents/QDialog/src/QDialogContainer/index.vue
>      beforeClose: {
этому тут не место, плюс оно не используется

2021-09-17 14:25 UTC, ViZhe commented on src/qComponents/index.ts
> +import './QDialog/src/QDialogContainer/q-dialog.scss';
должно остаться `import './QDialog/src/q-dialog.scss';`

2021-09-17 14:25 UTC, ViZhe commented on stories/plugins/QDialog/Default.stories.ts
> +  title: 'Plugins/QDialog',
Plugins/QDialog/Component

2021-09-17 14:25 UTC, ViZhe commented on stories/plugins/QDialog/Default.stories.ts
> +          console.log('event:', result);
console.log('resolve', result);

2021-09-17 14:25 UTC, ViZhe commented on stories/plugins/QDialog/Default.stories.ts
> +          console.log(e);
console.log('reject', err);

2021-09-17 14:25 UTC, ViZhe commented on stories/plugins/QDialog/Default.stories.ts
> +    template: `
template: '<q-button @click="handleClick">Click to open</q-button>'

2021-09-17 14:25 UTC, ViZhe commented on stories/plugins/QDialog/Default.stories.ts
> +export const Default = QDialogStory.bind({});
export const Component = QDialogComponentStory.bind({});

2021-09-17 14:25 UTC, ViZhe commented on stories/plugins/QDialog/DialogFormTest.vue
> +  <h2>Morbi massa libero, vehicula nec consequat sed, porta a sem.</h2>
заголовок диалога !== h2

2021-09-17 14:25 UTC, ViZhe commented on stories/plugins/QDialog/DialogFormTest.vue
> +import { defineComponent, reactive, ref } from 'vue';
перенос после

2021-09-17 14:25 UTC, ViZhe commented on stories/plugins/QDialog/DialogFormTest.vue
> +import QFormItem from '@/qComponents/QFormItem/src/QFormItem.vue';
это всё из '@/qComponents' нужно брать

2021-09-17 14:25 UTC, ViZhe commented on stories/plugins/QDialog/DialogFormTest.vue
> +  name: 'DialogFormTest',
перенос после

2021-09-17 14:25 UTC, ViZhe commented on stories/plugins/QDialog/DialogFormTest.vue
> +  components: { QFormItem, QButton, QInput, QForm },
перенос после

2021-09-17 14:25 UTC, ViZhe commented on stories/plugins/QDialog/DialogFormTest.vue
> +  },
перенос после

2021-09-17 14:25 UTC, ViZhe commented on stories/plugins/QDialog/Extended.stories.ts
> +import { Default } from './Default.stories';
откуда такое чудо взялось)

2021-09-17 14:25 UTC, ViZhe commented on stories/plugins/QDialog/Extended.stories.ts
> +import { QDialogOptions } from '@/qComponents/QDialog/src/types';
`'@/qComponents'`

2021-09-17 14:25 UTC, ViZhe commented on stories/plugins/QDialog/Extended.stories.ts
> +          console.log('event:', result);
console.log('resolve', result);

2021-09-17 14:25 UTC, ViZhe commented on stories/plugins/QDialog/Extended.stories.ts
> +          console.log(e);
console.log('reject', err);

2021-09-17 14:25 UTC, ViZhe commented on stories/plugins/QDialog/Extended.stories.ts
> +    template: `
template: '<q-button @click="handleClick">Click to open</q-button>'

2021-09-17 14:25 UTC, ViZhe commented on stories/plugins/QDialog/Extended.stories.ts
> +Default.args = {
Extended

2021-09-20 09:45 UTC, ViZhe requested changes

2021-09-20 09:45 UTC, ViZhe commented on src/qComponents/QDialog/src/QDialogContainer/index.vue
> +    const zIndex = ref<number>(getConfig('nextZIndex') ?? DEFAULT_Z_INDEX);
const zIndex = getConfig('nextZIndex');

2021-09-20 09:45 UTC, ViZhe commented on stories/plugins/QDialog/Default.stories.ts
> +            { ...args, teleportTo: 'body' }
`teleportTo: 'body'` лишнее

2021-09-20 09:45 UTC, ViZhe commented on stories/plugins/QDialog/DialogFormTest.vue
> +  <h1>Morbi massa libero, vehicula nec consequat sed, porta a sem.</h1>
h1 все еще не тоже самое что заголовок диалога

2021-09-20 09:45 UTC, ViZhe commented on stories/plugins/QDialog/Default.stories.ts
> +    closeOnClickShadow: { control: { type: 'boolean', default: true } }
`default: true` лишнее так как внизу args определяются

2021-09-20 09:45 UTC, ViZhe commented on stories/plugins/QDialog/Extended.stories.ts
> +    template: `<q-button @click="handleClick">Click to open</q-button>`
стоит использовать обычные ковычки

2021-09-20 09:45 UTC, ViZhe commented on stories/plugins/QDialog/Default.stories.ts
> +    template: `<q-button @click="handleClick">Click to open</q-button>`
стоит использовать обычные ковычки

2021-09-20 09:45 UTC, ViZhe commented on stories/plugins/QDialog/Default.stories.ts
> +};
в целом нет смысла определять args если они равны дефолтным

2021-09-20 09:45 UTC, ViZhe commented on src/qComponents/QDialog/index.ts
> +export type { QDialogOptions } from './src/types';
QDialog, QDialogOptions

2021-09-20 09:45 UTC, ViZhe commented on src/qComponents/QDialog/src/QDialogContainer/index.vue
>  const DEFAULT_Z_INDEX = 2000;
лишнее

2021-09-20 09:45 UTC, ViZhe commented on src/qComponents/QDialog/src/QDialogContainer/index.vue
> +      closeDialog({ action: QDialogAction.close });
стоит добавить пропс `distinguishCancelAndClose` и разнести тут на close/cancel

2021-09-20 09:45 UTC, ViZhe commented on src/qComponents/QDialog/src/QDialogContainer/types.ts
> +import { Component, ComputedRef, Ref } from 'vue';
import type

2021-09-20 09:45 UTC, ViZhe commented on src/qComponents/QDialog/src/QDialogContainer/types.ts
> +export interface QDialogContainerProps extends QDialogOptions {
продублируй тут пропсы из QDialogOptions и избавься от extends

2021-09-20 09:45 UTC, ViZhe commented on src/qComponents/QDialog/src/QDialogContainer/types.ts
> +export type QDialogContainerPropTeleportTo = Nullable<string | HTMLElement>;
перед QDialogContainerProps

2021-09-20 09:45 UTC, ViZhe commented on src/qComponents/QDialog/src/types.ts
> +import { App, ComponentInternalInstance } from 'vue';
import type

2021-09-20 09:45 UTC, ViZhe commented on src/qComponents/QDialog/src/types.ts
> +import {
type

2021-09-20 09:45 UTC, ViZhe commented on src/qComponents/QDialog/src/types.ts
> +import { QDialogAction } from './constants';
type

2021-09-20 09:45 UTC, ViZhe commented on src/qComponents/QDialog/src/types.ts
> +import { QDialogContainerPropTeleportTo } from '@/qComponents/QDialog/src/QDialogContainer/types';
type

2021-09-20 09:45 UTC, ViZhe commented on stories/plugins/QDialog/Default.stories.ts
> +  }
стоит так же добавить customClass

2021-09-20 15:34 UTC, ViZhe requested changes

2021-09-20 15:34 UTC, ViZhe commented on src/qComponents/QDialog/src/QDialogContent/index.vue
> +    <div class="q-dialog-content__content">
q-dialog-content__body

2021-09-20 15:34 UTC, ViZhe commented on stories/plugins/QDialog/Extended.stories.ts
> +  closeOnClickShadow: true
это и так тру по дефолту

2021-09-20 15:34 UTC, ViZhe commented on stories/plugins/QDialog/DialogFormTest.vue
> +import { QDialogContent } from '@/qComponents/QDialog';
из '@/qComponents'

2021-09-20 15:34 UTC, ViZhe commented on src/qComponents/QDialog/src/QDialogContent/index.vue
> +      <slot name="content" />
думаю есть смысл тут дефолтный слот оставить, а не именованный

2021-09-20 15:34 UTC, ViZhe commented on stories/plugins/QDialog/Component.stories.ts
> +  closeOnClickShadow: true
тоже дефолт

2021-09-20 15:34 UTC, ViZhe commented on stories/plugins/QDialog/Component.stories.ts
> +            { ...args, distinguishCancelAndClose: true }
нет смысла тут жестко задавать distinguishCancelAndClose

2021-09-20 15:34 UTC, ViZhe commented on stories/plugins/QDialog/Component.stories.ts
> +    customClass: { control: { type: 'text' } }
плюс distinguishCancelAndClose

2021-09-20 15:34 UTC, ViZhe commented on stories/plugins/QDialog/Extended.stories.ts
> +    customClass: { control: { type: 'text' } }
плюс distinguishCancelAndClose

2021-09-20 15:34 UTC, ViZhe commented on src/qComponents/QDialog/src/types.ts
> +import type { QDialogContainerPropTeleportTo } from '@/qComponents/QDialog/src/QDialogContainer/types';
автоимпорты зло

2021-09-20 15:34 UTC, ViZhe commented on src/qComponents/QDialog/src/QDialogContent/q-dialog-content.scss
> +    flex: 1;
вне флекс контейнера?

2021-09-20 15:34 UTC, ViZhe commented on src/qComponents/QDialog/src/QDialogContainer/q-dialog-container.scss
> +  }
тут нужно подумать

2021-09-20 15:34 UTC, ViZhe commented on src/qComponents/QDialog/src/QDialogContainer/index.vue
> +    'closed',
стоит удалить то что не эмитится

2021-09-20 15:34 UTC, ViZhe commented on src/qComponents/QDialog/src/QDialogContainer/types.ts
> +  onUnmounted?: (app: App<Element>) => void;
такого пропса нет в QDialogContainer

2021-09-21 07:48 UTC, Tim152 approved these changes

2021-09-23 09:24 UTC, ViZhe requested changes

2021-09-23 09:24 UTC, ViZhe commented on src/qComponents/QDialog/src/QDialogContainer/index.vue
> +    provide<QDialogContainerProvider>('QDialogContainer', { emitCloseEvent });
'qDialogContainer'

2021-09-23 09:24 UTC, ViZhe commented on src/qComponents/QDialog/src/QDialogContent/index.vue
> +    />
перенос строки после

2021-09-23 09:24 UTC, ViZhe commented on src/qComponents/QDialog/src/QDialogContent/index.vue
> +    <q-scrollbar
перенос строки перед

2021-09-23 09:24 UTC, ViZhe commented on src/qComponents/QDialog/src/QDialogContent/index.vue
> +import type { QDialogContainerProvider } from '../QDialogContainer/types';
`from '../QDialogContainer';`
и разместить чуть выше

2021-09-23 09:24 UTC, ViZhe commented on src/qComponents/QDialog/src/QDialogContent/index.vue
> +      {} as QDialogContainerProvider
null

2021-09-23 09:24 UTC, ViZhe commented on src/qComponents/QDialog/src/QDialogContent/index.vue
> +    const dialogContainer = inject<QDialogContainerProvider>(
первым в сетапе

2021-09-23 09:24 UTC, ViZhe commented on src/qComponents/QDialog/src/QDialogContent/index.vue
> +    beforeClose: {
это опция контейнера

2021-09-23 10:03 UTC, ViZhe requested changes

2021-09-23 10:03 UTC, ViZhe commented on src/qComponents/QDialog/src/QDialogContainer/q-dialog-container.scss
> +    padding: 36px 32px 32px;
думаю padding это часть контента скорее

2021-09-23 10:03 UTC, ViZhe commented on src/qComponents/QDialog/src/QDialogContainer/types.ts
> +import { QDialogAction } from '../constants';
import type

2021-09-23 10:03 UTC, ViZhe commented on src/qComponents/QDialog/src/QDialogContent/index.vue
> +import { Nullable } from '#/helpers';
после @/
и import type

2021-09-23 10:03 UTC, ViZhe commented on src/qComponents/QDialog/src/QDialogContent/q-dialog-content.scss
> +  &__body {
после view

2021-09-23 10:03 UTC, ViZhe commented on src/qComponents/QDialog/src/QDialogContent/q-dialog-content.scss
> +  &__close {
перед title

2021-09-23 10:03 UTC, ViZhe commented on src/qComponents/QDialog/src/QDialogContent/types.ts
> +import { Nullable } from '#/helpers';
impoty type

2021-09-23 10:14 UTC, ViZhe requested changes

2021-09-23 10:14 UTC, ViZhe commented on src/qComponents/QDialog/src/QDialogContainer/index.vue
> +    });
перенос строки после

2021-09-23 11:44 UTC, ViZhe requested changes

2021-09-23 11:44 UTC, ViZhe commented on src/qComponents/QDialog/src/QDialogContainer/q-dialog-container.scss
> +    position: relative;
это скорее всего лишнее

2021-09-23 11:44 UTC, ViZhe commented on src/qComponents/QDialog/src/QDialogContent/q-dialog-content.scss
> +  height: 100%;
а вот тут position relative будет выглядеть к месту, для позиционирования  close

2021-09-24 13:48 UTC, ViZhe requested changes

2021-09-24 13:48 UTC, ViZhe commented on src/qComponents/QDatePicker/src/QDatePicker.vue
> +    const dialog = useDialog();
лучше перед рефками это разместить и отступ после

2021-09-24 13:48 UTC, ViZhe commented on src/qComponents/QDatePicker/src/mobile/MobilePanel.vue
> +      @pick="handleClick"
тут клика не происходит

2021-09-24 13:48 UTC, ViZhe commented on src/qComponents/QDialog/src/index.ts
> +      const provides = { ...globalProvides, ...parentInstanceProvides };
вроде как нет профита их смешивать, то что доступно глобально доступно и в текущем инстансе, лучше сделай колбек на appContext

2021-09-24 13:48 UTC, ViZhe commented on src/qComponents/QDialog/src/types.ts
> +  provides: Record<string, unknown>;
там не всегда стринг

2021-09-24 13:48 UTC, ViZhe commented on src/qComponents/QDialog/src/types.ts
> +export interface QDialogParentInstance extends ComponentInternalInstance {
QDialogParentInstance конфузит, лучше уж чтото в духе
ComponentInternalInstanceWithProvides

2021-09-24 13:48 UTC, ViZhe commented on src/qComponents/QDatePicker/src/mobile/MobilePanel.vue
> +      picker.handlePickClick(val);
это стоит делать в QDatePicker.vue

2021-09-24 13:48 UTC, ViZhe commented on src/qComponents/QDatePicker/src/mobile/MobilePanel.vue
> +    const panelComponent = computed<
это уже есть в QDatePicker.vue наверняка можно переиспользовать

2021-09-24 13:48 UTC, ViZhe commented on src/qComponents/QDatePicker/src/mobile/MobilePanel.vue
> +      dialog.closeDialog({ action: QDialogAction.confirm, payload: val });
`dialog.closeDialog`
тавтологичненько, мб сделать close или emitDoneEvent или чтото в таком духе

2021-09-24 13:48 UTC, ViZhe commented on src/qComponents/QDatePicker/src/mobile/MobilePanel.vue
> +import { QDialogContent } from '@/qComponents/QDialog/src/QDialogContent';
@/qComponents/QDialog

2021-09-24 13:48 UTC, ViZhe commented on src/qComponents/QDatePicker/src/mobile/MobilePanel.vue
> +import { QDialogAction } from '@/qComponents';
@/qComponents/QDialog

2021-09-24 13:48 UTC, ViZhe commented on src/qComponents/QDatePicker/src/mobile/MobilePanel.vue
> +import type { QDialogContainerProvider } from '@/qComponents/QDialog/src/QDialogContainer';
@/qComponents/QDialog

2021-09-24 13:48 UTC, ViZhe commented on src/qComponents/QDatePicker/src/mobile/MobilePanel.vue
> +  components: { QDialogContent },
перенос перед

2021-09-24 14:05 UTC, ViZhe requested changes

2021-09-24 14:05 UTC, ViZhe commented on src/qComponents/QDatePicker/src/QDatePicker.vue
> +      transformedToDate: toRef(transformedToDate, 'value'),
?? зачем computed в реф перегонять?

2021-09-24 14:05 UTC, ViZhe commented on src/qComponents/QDatePicker/src/mobile/MobilePanel.vue
> +      v-model="picker.transformedToDate.value"
`:model-value="` и в QDatePicker.vue где transformedToDate прокидывается тож нужно поправить

2021-09-27 10:42 UTC, ViZhe requested changes

2021-09-27 10:42 UTC, ViZhe commented on src/qComponents/QDatePicker/src/mobile/types.ts
> +import type { QDialogContainerProvider } from '@/qComponents/QDialog';
перед ../types и перенос после

2021-09-27 10:42 UTC, ViZhe commented on src/qComponents/QDatePicker/src/QDatePicker.vue
> +        if (result) emitChange(result.payload as QDatePickerPropModelValue);
разве отсутствовать result?

2021-09-27 10:42 UTC, ViZhe commented on src/qComponents/QDatePicker/src/QDatePicker.vue
> +            customClass: 'q-date-picker-dialog'
в этом нет необходимости, перенеси все стили которые относятся к MobilePanel ближе к MobilePanel

2021-09-27 10:42 UTC, ViZhe commented on src/qComponents/QDatePicker/src/QDatePicker.vue
> +        state.pickerVisible = false;
finally либо просто после трукеч блока, дублировать нет смысла

2021-09-27 10:42 UTC, ViZhe commented on src/qComponents/QDatePicker/src/mobile/MobilePanel.vue
> +    :model-value="picker.transformedToDate.value"
.value лишнее и выше

2021-09-27 10:42 UTC, ViZhe commented on src/qComponents/QDatePicker/src/types.ts
> +  >;
есть смысл вынести это в тип и переиспользовать

2021-09-27 10:42 UTC, ViZhe commented on src/qComponents/QDatePicker/src/types.ts
> +type QDatePickerPropTrasformedToDate = Nullable<Date | Date[]>;
это не Prop

2021-09-27 10:42 UTC, ViZhe commented on src/qComponents/QDatePicker/src/mobile/MobilePanel.vue
> +    const handlePick = (val: QDatePickerPropModelValue): void => {
val в payload

2021-09-27 10:42 UTC, ViZhe commented on src/qComponents/QDatePicker/src/mobile/MobilePanel.vue
> +    class="q-mobile-panel-close"
q-dialog-mobile-panel__close

2021-09-27 10:47 UTC, ViZhe requested changes

2021-09-27 10:47 UTC, ViZhe commented on src/qComponents/QDialog/src/QDialogContent/index.vue
> +  setup(): QDialogContentInstance {
```
// eslint-disable-next-line @typescript-eslint/no-unused-vars
setup(props: QDialogContentProps): QDialogContentInstance {
```

2021-09-27 10:47 UTC, ViZhe commented on src/qComponents/QDialog/src/QDialogContent/index.ts
> +export type { QDialogContentProps } from './types';
плюс QDialogContentInstance

2021-09-27 10:47 UTC, ViZhe commented on src/qComponents/QDialog/index.ts
> +export type { QDialogContentProps } from './src/QDialogContent';
плюс QDialogContentInstance

2021-09-27 10:47 UTC, ViZhe commented on src/qComponents/QDialog/index.ts
> +import { QDialog, QDialogHookOptions } from './src/types';
import type

2021-09-27 11:37 UTC, SeregaBB commented on src/qComponents/QDatePicker/src/mobile/MobilePanel.vue
> +    const handlePick = (val: QDatePickerPropModelValue): void => {
он уже там )

2021-09-27 12:03 UTC, SeregaBB commented on src/qComponents/QDatePicker/src/mobile/MobilePanel.vue
> +    :model-value="picker.transformedToDate.value"
ESLint говорит ":is should go before :model-value"

2021-09-27 13:43 UTC, ViZhe requested changes

2021-09-27 13:43 UTC, ViZhe commented on src/qComponents/QDatePicker/src/QDatePicker.vue
> +      } catch (err) {
} catch  {

2021-09-27 13:43 UTC, ViZhe commented on src/qComponents/QDatePicker/src/mobile/MobilePanel.vue
> +      dialog,
handleCloseBtnClick:dialog.emitCloseEvent

2021-09-27 13:43 UTC, ViZhe commented on src/qComponents/QDatePicker/src/mobile/MobilePanel.vue
> +    const handlePick = (val: QDatePickerPropModelValue): void => {
переименовать)

2021-09-27 13:43 UTC, ViZhe commented on src/qComponents/QDatePicker/src/panel/q-picker-panel.scss
>    &__dialog-view {
нужно прям все стили связанные с MobilePanel перенести в MobilePanel

2021-09-27 13:43 UTC, ViZhe commented on src/qComponents/QDialog/src/QDialogContainer/index.vue
> +              @done="closeDialog"
мб это лишнее уже, провайд гибче и понятнее в этом кейсе

2021-09-27 13:43 UTC, ViZhe commented on src/qComponents/QDialog/src/QDialogContainer/index.vue
> +const DONE_EVENT = 'done';
дропни константы в пользу просто строк

2021-09-27 13:43 UTC, ViZhe commented on src/qComponents/QDialog/src/QDialogContainer/index.vue
> +  components: { QButton, QScrollbar },
QButton лишнее

2021-09-27 13:43 UTC, ViZhe commented on src/qComponents/QDialog/src/QDialogContainer/index.vue
> +      close: closeDialog,
emitDoneEvent
а то одновременно close и emitCloseEvent конфузит

2021-09-27 13:43 UTC, ViZhe commented on src/qComponents/QDialog/src/QDialogContent/index.vue
> +    const handleClose = async (): Promise<void> => {
async лишнее

2021-09-27 13:43 UTC, ViZhe commented on src/qComponents/QDialog/src/types.ts
> +  reject: (evt: QDialogEvent) => void;
(event: QDialogEvent) и выше

2021-09-28 08:59 UTC, ViZhe requested changes

2021-09-28 08:59 UTC, ViZhe commented on src/qComponents/QDatePicker/src/mobile/MobilePanel.vue
> +import { QButton } from '@/qComponents';
@/qComponents/QButton

2021-09-28 08:59 UTC, ViZhe commented on src/qComponents/QDatePicker/src/mobile/MobilePanel.vue
> +
перенос лишний

2021-09-28 08:59 UTC, ViZhe commented on src/qComponents/QDatePicker/src/mobile/MobilePanel.vue
> +import type { QDialogContainerProvider } from '@/qComponents/QDialog';
перенос после

2021-09-28 08:59 UTC, ViZhe commented on src/qComponents/QDatePicker/src/mobile/MobilePanel.vue
> +import type { MobilePanelInstance } from './types';
последний импорт по порядку

2021-09-28 08:59 UTC, ViZhe commented on src/qComponents/QDatePicker/src/mobile/MobilePanel.vue
> +  emits: ['done'],
дропни

2021-09-28 08:59 UTC, ViZhe commented on src/qComponents/QDatePicker/src/mobile/q-dialog-mobile-panel.scss
> +      &-wrapper {
перенос перед

2021-09-28 08:59 UTC, ViZhe commented on src/qComponents/QDialog/index.ts
> +
добавт анмаунт диалога при анмаунте родителя

2021-09-28 08:59 UTC, ViZhe commented on stories/plugins/QDialog/DialogFormTest.vue
> +const NAME_INPUT_EVENT = 'name-input';
дропни константу в пользу просто строки

2021-09-28 08:59 UTC, ViZhe commented on stories/plugins/QDialog/DialogFormTest.vue
> +    <template #default>
лишняя обёртка

2021-09-28 08:59 UTC, ViZhe commented on stories/plugins/QDialog/DialogFormTest.vue
> +    const dialogProvides = inject<QDialogContainerProvider>('qDialogContainer');
const qDialogContainer =

2021-09-28 08:59 UTC, ViZhe commented on src/qComponents/QDatePicker/src/mobile/types.ts
> +import { QDatePickerPanelComponent } from '../types';
import types

2021-09-28 08:59 UTC, ViZhe commented on src/qComponents/QDatePicker/src/mobile/types.ts
> +import { QDatePickerPanelComponent } from '../types';
но вообще объединить с предыдущим

2021-09-28 08:59 UTC, ViZhe commented on stories/plugins/QDialog/DialogFormTest.vue
> +  QFormItem,
QForm,
  QInput,
  QButton,
  QFormItem
  лишнее

2021-09-29 07:21 UTC, ViZhe approved these changes

2021-09-30 07:59 UTC, Tim152 approved these changes

2021-09-30 08:17 UTC, merged