[Icons] Add icons story
Qvant-lab/qui-max pull request #165
Opened 2021-09-28 15:20 UTC by SeregaBB

2021-09-29 07:44 UTC, ViZhe requested changes

2021-09-29 07:44 UTC, ViZhe commented on stories/core/Icons.stories.ts
> +          </div>
добавить бы копирование класса при клике

2021-09-29 07:44 UTC, ViZhe commented on stories/core/Icons.stories.ts
> +  title: 'Core/Icons/Icons'
Icons/Icons не очень понятно

2021-09-29 07:44 UTC, ViZhe commented on stories/core/Icons.stories.ts
> +    },
дать бы возможность изменять размер всех иконок через сторибучный бар

2021-09-29 07:44 UTC, ViZhe commented on stories/core/Icons.stories.ts
> +
mdx историю тоже нужно переписать в дефолтной манере

2021-09-29 07:44 UTC, ViZhe commented on stories/core/Icons.stories.ts
> +          class="q-icons__icon-container"
q-icons__container

2021-09-29 07:44 UTC, ViZhe commented on stories/core/Icons.stories.ts
> +          <div class="q-icons__icon-wrapper">
q-icons__wrapper

2021-09-29 07:44 UTC, ViZhe commented on stories/core/Icons.stories.ts
> +              class="q-icons__icon"
q-icons__preview

2021-09-29 07:44 UTC, ViZhe commented on stories/core/Icons.stories.ts
> +          <div class="q-icons__icon-class">
q-icons__name

2021-09-29 15:13 UTC, ViZhe requested changes

2021-09-29 15:13 UTC, ViZhe commented on stories/core/Icons.stories.ts
> +          minHeight: `${args.fontSize * 1.25}px`
наверняка есть способ не рассчитывать это и сохранить текущее поведение

2021-09-29 15:13 UTC, ViZhe commented on stories/core/Icons.stories.ts
> +        if (visibleTooltip.value) {
if (!visibleTooltip.value) return

2021-09-29 15:13 UTC, ViZhe commented on stories/core/Icons.stories.ts
> +      };
в том же порядке что объявляются

2021-09-29 15:13 UTC, ViZhe commented on stories/core/Icons.stories.ts
> +      }));
в данном случае нет смысла в этом компутеде

2021-09-30 10:40 UTC, ViZhe requested changes

2021-09-30 10:40 UTC, ViZhe commented on stories/core/Icons.stories.ts
> +import { Nullable } from '#/helpers';
import type

2021-09-30 10:40 UTC, ViZhe commented on stories/core/Icons.stories.ts
> +                class="q-icons__tooltip"
2 пробела от начала тега

2021-09-30 10:40 UTC, ViZhe commented on stories/core/Icons.stories.ts
> +              @click="handleIconClick(icon)"
тут тоже 2 пробела

2021-09-30 10:40 UTC, ViZhe commented on stories/core/Icons.stories.ts
> +              :style="fontSize"
задай размер цсс переменной и потом переопределяй эту переменную у всего блока `q-icons`

2021-09-30 10:40 UTC, ViZhe commented on stories/core/icons.scss
> +  &__tooltip {
порядок элементов стоит соблюсти из разметки

2021-09-30 13:44 UTC, ViZhe requested changes

2021-09-30 13:44 UTC, ViZhe commented on stories/core/icons.scss
> +  --font-size: 32px;
переменные лучше перед стилями размещать, так как они могут использоваться в них уже

2021-09-30 13:44 UTC, ViZhe commented on stories/core/playground.stories.ts
> +    template: `
тут можно в одну строчку, раз он маленький
`' <span :class="icon" :style="style" />'`

2021-09-30 13:51 UTC, ViZhe approved these changes

2021-10-04 14:42 UTC, Tim152 approved these changes

2021-10-04 14:42 UTC, merged