QSlider - fix types
Qvant-lab/qui-max pull request #255
Opened 2022-03-24 08:38 UTC by shamilfrontend

2022-03-24 10:22 UTC, SeregaBB requested changes

2022-03-24 10:22 UTC, SeregaBB commented on src/qComponents/QSlider/src/components/QSliderBar/types.ts
> +export type BarStyle = Record<string, Nullable<string>>;
```suggestion
export type BarStyle = Record<string, Nullable<string | number>>;
```

2022-03-25 11:48 UTC, SeregaBB approved these changes

2022-03-25 12:01 UTC, skaflock commented on src/qComponents/QSlider/src/components/QSliderCaptions/types.ts
> +export type Classes = Record<string, boolean>;
Этот тип наверное будет много где встречаться - может есть смысл вынести его отдельно?

2022-03-25 12:16 UTC, skaflock approved these changes

2022-03-25 12:22 UTC, shamilfrontend commented on src/qComponents/QSlider/src/components/QSliderCaptions/types.ts
> +export type Classes = Record<string, boolean>;
к примеру в "qComponents/types.ts" ?) или куда

2022-03-25 12:24 UTC, skaflock commented on src/qComponents/QSlider/src/components/QSliderCaptions/types.ts
> +export type Classes = Record<string, boolean>;
Да, я бы вынес туда

2022-03-25 12:43 UTC, shamilfrontend commented on src/qComponents/QSlider/src/components/QSliderCaptions/types.ts
> +export type Classes = Record<string, boolean>;
@ViZhe @Tim152 что скажете?

2022-03-25 20:33 UTC, ViZhe requested changes

2022-03-25 20:33 UTC, ViZhe commented on src/qComponents/QSlider/src/components/QSliderCaptions/types.ts
> +export type Classes = Record<string, boolean>;
make sense

2022-03-25 20:39 UTC, ViZhe commented on src/qComponents/QSlider/src/types.ts
>    label: string;
сделай необязательным

2022-03-25 20:40 UTC, ViZhe commented on src/qComponents/QSlider/src/components/QSliderCaptions/QSliderCaptions.vue
> +    const getCaptionItemClasses = (value: QSliderPropModelValue): Classes => ({
тип аргумента некорретный

2022-03-25 20:43 UTC, ViZhe commented on src/qComponents/QSlider/src/types.ts
>  export interface QSliderPropData {
```suggestion
export interface QSliderData {
```

2022-03-25 20:44 UTC, ViZhe commented on src/qComponents/QSlider/src/types.ts
export type QSliderPropData = QSliderData[]

2022-03-25 20:44 UTC, ViZhe commented on src/qComponents/QSlider/src/types.ts
>    data: QSliderPropData[];
```suggestion
  data: QSliderPropData;
```

2022-03-25 21:04 UTC, ViZhe commented on src/qComponents/QSlider/src/types.ts
> +export type QSliderPropModelValue = Nullable<ModelValue>;
```suggestion
export type QSliderPropModelValue< T extends Nullable<ModelValue> = Nullable<ModelValue>> = T;
```

2022-03-28 14:11 UTC, ViZhe commented on src/qComponents/types.ts
> +export type Classes = Record<string, boolean>;
в #/helpers

2022-03-28 16:36 UTC, ViZhe commented on types/helpers.ts
> +export type Classes = Record<string, boolean>;
ClassValue

2022-03-28 19:53 UTC, ViZhe commented on src/qComponents/QSlider/src/types.ts
> +interface QSliderData {
тоже лучше через generic сделать

2022-03-28 19:53 UTC, ViZhe commented on types/helpers.ts
> +export type Classes = Record<string, boolean>;
тип не полный

2022-04-01 15:20 UTC, ViZhe commented on stories/components/QSlider/SlotCaption.ts
> +  [key: number]: number;
лишнее

2022-04-01 15:25 UTC, ViZhe commented on stories/components/QSlider/Default.ts
> +type ModelValue = 'easy' | 'normal' | 'hard';
```suggestion
type ModelValue = QSliderPropModelValue<'easy' | 'normal' | 'hard'>;
```

2022-04-01 15:25 UTC, ViZhe commented on stories/components/QSlider/Default.ts
> +      const value = ref<QSliderPropModelValue<ModelValue>>('easy');
```suggestion
      const value = ref<ModelValue>('easy');
```

2022-04-01 15:25 UTC, ViZhe commented on stories/components/QSlider/Default.ts
> +const data: QSliderPropData = [
```suggestion
const data: QSliderPropData<ModelValue> = [
```

2022-04-01 15:25 UTC, ViZhe commented on stories/components/QSlider/SlotCaption.ts
> +type ModelValue = 'easy' | 'normal' | 'hard';
тоже самое что и в stories/components/QSlider/Default.ts

2022-04-01 16:52 UTC, ViZhe approved these changes

2022-04-06 16:22 UTC, Tim152 approved these changes

2022-04-06 16:23 UTC, merged