fix(QScrollbar): types
Qvant-lab/qui-max pull request #256
Opened 2022-03-24 11:02 UTC by shamilfrontend

2022-04-04 10:44 UTC, skaflock commented on src/qComponents/QScrollbar/src/components/QBar/util.ts
> +  style['-ms-transform'] = translate;
Трансформы работают без префиксов, начиная с IE10: https://caniuse.com/?search=transform 

Я бы убрал использование префиксов

2022-04-04 11:35 UTC, shamilfrontend commented on src/qComponents/QScrollbar/src/components/QBar/util.ts
> +  style['-ms-transform'] = translate;
убрал)

2022-04-06 10:22 UTC, SeregaBB requested changes

2022-04-06 10:22 UTC, SeregaBB commented on src/qComponents/QScrollbar/src/components/QBar/util.ts
>  export const BAR_MAP: Record<'vertical' | 'horizontal', BarMapItem> = {
мб вместо 'vertical' | 'horizontal' тоже тип использовать, напр Types или отдельный сделать напр. BarMapKey. + почему BAR_MAP лежит в util.ts а не в constants.ts

2022-04-06 11:58 UTC, shamilfrontend commented on src/qComponents/QScrollbar/src/components/QBar/util.ts
>  export const BAR_MAP: Record<'vertical' | 'horizontal', BarMapItem> = {
вижу похожий тип в types, порефачу, спс)

2022-05-17 12:28 UTC, ViZhe commented on src/qComponents/QScrollbar/src/QScrollbar.vue
> +      :theme="theme ?? 'primary'"
думаю с этим нужно чтото сделать

2022-05-17 13:22 UTC, ViZhe commented on src/qComponents/QScrollbar/src/QScrollbar.vue
> +import type { QBarInstance } from './components/QBar/types';
из индекс файла

2022-05-17 13:23 UTC, ViZhe requested changes

2022-05-17 13:23 UTC, ViZhe commented on src/qComponents/QScrollbar/src/QScrollbar.vue
> +import type { QBarInstance } from './components/QBar/types';
из индекс файла

2022-05-18 10:38 UTC, ViZhe commented on src/qComponents/QScrollbar/src/components/QBar/index.ts
> +export { QBarInstance } from './types';
type

2022-05-18 13:24 UTC, ViZhe approved these changes

2022-05-18 13:51 UTC, Tim152 approved these changes

2022-05-18 13:52 UTC, merged