docs(QScrollbar): add QScrollbar docs
Qvant-lab/qui-max pull request #259
Opened 2022-03-25 10:23 UTC by SeregaBB

2022-03-25 11:55 UTC, ViZhe requested changes

2022-03-25 11:55 UTC, ViZhe commented on vuepress-docs/docs/components/QScrollbar.md
> +- Type: `'primary'|'secondary'`
```suggestion
- Type: `'primary' | 'secondary'`
```

2022-03-25 11:55 UTC, ViZhe commented on vuepress-docs/docs/components/QScrollbar.md
> +<q-scrollbar>Lorem ipsum dolor...</q-scrollbar>
наверное лучше вот так и в примере тоже, без visible уже есть пример выше в theme
```suggestion
<q-scrollbar theme="secondary" visible>Lorem ipsum dolor...</q-scrollbar>
```

2022-03-25 11:55 UTC, ViZhe commented on vuepress-docs/docs/components/QScrollbar.md
> +QScrollbar main content
вот тут погляди как в других местах описано, а то слишком сухо получилось

2022-03-25 12:15 UTC, Tim152 commented on vuepress-docs/docs/components/QScrollbar.md
> +
```suggestion
- Default: `false` 
```

2022-03-25 12:15 UTC, Tim152 commented on vuepress-docs/docs/components/QScrollbar.md
> +
Добавь раздел Example, он подразумевает дефолтное состояние компонента или набор состояний

2022-03-25 12:15 UTC, Tim152 commented on vuepress-docs/docs/components/QScrollbar.md
> +- Type: `Object|String|Array`
добавь везде дефолты и пробелы между |

2022-03-25 12:15 UTC, Tim152 commented on vuepress-docs/docs/components/QScrollbar.md
> +### scrollTo
не плохо бы замутить примерчик интерактивный, - скроллить по кнопке

2022-03-29 12:59 UTC, ViZhe approved these changes

2022-03-29 13:21 UTC, merged