feat(QTabs): update design
Qvant-lab/qui-max pull request #271
Opened 2022-04-19 17:00 UTC by skaflock

2022-04-19 20:10 UTC, ViZhe requested changes

2022-04-19 20:10 UTC, ViZhe commented on src/qComponents/QTabPane/src/q-tab-pane.scss
> +  &:first-child &__btn {
лучше перенести в блок стилей кнопки и использовать селектор вида `.q-tab-pane:first-child &`

2022-04-20 09:51 UTC, skaflock commented on src/qComponents/QTabPane/src/q-tab-pane.scss
> +    &.focus-visible {
я считаю, что стоит оставить отображение фокуса - и в системных интерфейсах, и в том же бутстрапе можно фокусить активный элемент (а иначе как определить где сейчас находится фокус?)

2022-04-20 10:07 UTC, skaflock commented on src/qComponents/QTabPane/src/q-tab-pane.scss
> +  --shadow-large: 4px 4px 8px rgb(var(--color-rgb-blue) / 40%),
на эту тему, наверное, надо с Лёшей поговорить - зачем там тень, отличающаяся на 1 пиксель радиусом размытия

я, например, не вижу разницы https://codepen.io/skaflock/pen/MWrLZJe

2022-04-20 10:37 UTC, skaflock commented on src/qComponents/QTabPane/src/q-tab-pane.scss
> +      outline: 1px solid var(--color-primary-blue);
@ViZhe поправил

2022-04-20 10:37 UTC, skaflock commented on src/qComponents/QTabPane/src/q-tab-pane.scss
> +    letter-spacing: 0.03em;
@ViZhe поправил

2022-04-20 10:40 UTC, skaflock commented on src/qComponents/QTabPane/src/q-tab-pane.scss
> +      box-shadow: var(--shadow-large);
@ViZhe поправил (хотя нужно Лёшу спросить - может ли быть active+hover)

2022-04-20 10:40 UTC, skaflock commented on src/qComponents/QTabPane/src/q-tab-pane.scss
> +  &:first-child &__btn {
@ViZhe поправил

2022-04-20 10:41 UTC, skaflock commented on src/qComponents/QTabPane/src/q-tab-pane.scss
>        color: var(--color-primary-black);
@ViZhe поправил

2022-04-20 11:14 UTC, ViZhe commented on src/qComponents/QTabPane/src/q-tab-pane.scss
>    &__description {
дропни всё что связано с description в том числе пропс и в шаблоне

2022-04-20 11:54 UTC, ViZhe commented on src/qComponents/QTabPane/src/QTabPane.vue
> -    description: {
в документации тоже, вероятно нужно обновить саму ветку от мейна

2022-04-20 11:56 UTC, skaflock commented on src/qComponents/QTabPane/src/q-tab-pane.scss
>    &__description {
@ViZhe сделано

2022-04-20 11:56 UTC, skaflock commented on src/qComponents/QTabPane/src/QTabPane.vue
> -    description: {
@ViZhe сделано

2022-04-20 11:57 UTC, skaflock commented on src/qComponents/QTabPane/src/q-tab-pane.scss
> +    &.focus-visible {
@ViZhe сделал кнопку disabled, чтобы не фокусилась

2022-04-20 12:00 UTC, skaflock commented on src/qComponents/QTabPane/src/q-tab-pane.scss
> +      box-shadow: var(--shadow-large);
@ViZhe поправил еще раз по итогам обсуждения (активная кнопкка теперь не фокусируется и не ховерится)

2022-04-20 15:19 UTC, ViZhe approved these changes

2022-04-21 09:43 UTC, Tim152 approved these changes

2022-04-21 09:44 UTC, merged