feat(QSwitcher): add QSwitcher component
Qvant-lab/qui-max pull request #280
Opened 2022-04-27 12:24 UTC by SeregaBB

2022-04-27 12:31 UTC, ViZhe commented on src/qComponents/QSwitcher/src/q-switcher.scss
> +    display: none;
тут погляди как в QCheckbox прячется инпут

2022-04-27 12:31 UTC, ViZhe commented on src/qComponents/QSwitcher/src/q-switcher.scss
> +  :focus-visible:not(&_disabled) {
focus-visible через класс

2022-04-27 12:32 UTC, ViZhe commented on src/qComponents/QSwitcher/src/q-switcher.scss
> +  &__circle {
лучше уйти в нейминге от визуальной формы

2022-04-27 17:57 UTC, ViZhe commented on src/qComponents/QSwitcher/src/QSwitcher.vue
> +  name: 'QSwitcher',
```suggestion
  name: 'QSwitch',
```

2022-04-27 18:00 UTC, ViZhe commented on src/qComponents/QSwitcher/src/QSwitcher.vue
> +    };
выглядит лишнимс

2022-04-27 18:01 UTC, ViZhe commented on src/qComponents/QSwitcher/src/QSwitcher.vue
> +      ctx.emit('change', props.activeValue);
можно упростить наверняка

2022-04-27 18:02 UTC, ViZhe commented on src/qComponents/QSwitcher/src/QSwitcher.vue
> +    const tabIndex = computed<-1 | 0>(() => (props.disabled ? -1 : 0));
стоит вынести тип в types и там использовать не просто number

2022-04-27 18:16 UTC, ViZhe commented on src/qComponents/QSwitcher/src/QSwitcher.vue
> +      <div class="q-switcher__slider">
```suggestion
      <div class="q-switcher__handle">
```

2022-04-27 18:17 UTC, ViZhe commented on src/qComponents/QSwitcher/src/QSwitcher.vue
> +import type { QSwitcherInstance, QSwitcherProps } from './types';
```suggestion
import type { QSwitcherProps, QSwitcherInstance } from './types';
```

2022-04-27 18:19 UTC, ViZhe commented on src/qComponents/QSwitcher/src/q-switcher.scss
> +  &.focus-visible:not(&_disabled) {
а при _disabled вообще он тут вешает focus-visible?

2022-04-27 18:20 UTC, ViZhe commented on src/qComponents/QSwitcher/src/q-switcher.scss
> +      --icon-size: 12px;
нет смысла в этой переменной

2022-04-27 18:22 UTC, ViZhe commented on src/qComponents/QSwitcher/src/q-switcher.scss
> +      border: 2px solid var(--color-primary-darker);
в случае если бы это не решалось переменной то тут стоило использовать border-color так как размер обводки и её тип не меняется

2022-04-28 13:24 UTC, SeregaBB commented on src/qComponents/QSwitcher/src/q-switcher.scss
> +  &.focus-visible:not(&_disabled) {
да, если кликнуть на него, а потом нажать пробел/enter

2022-04-28 16:00 UTC, ViZhe commented on src/qComponents/QSwitch/src/QSwitch.vue
> +      const { disabled, loading, inactiveValue, activeValue } = props;
вроде бы нет профита от деструктуризации тут

2022-04-28 20:56 UTC, ViZhe commented on stories/components/QSwitch.stories.ts
> +import type { QSwitchProps } from '@/qComponents/QSwitch';
```suggestion
import type { QSwitchProps } from '@/qComponents';
```

2022-04-28 20:56 UTC, ViZhe commented on stories/components/QSwitch.stories.ts
> +        <q-switch v-model="isOn" :loading="args.loading" :disabled="args.disabled" :active-value="args.activeValue" :inactive-value="args.inactiveValue"  />
переносов

2022-04-28 20:59 UTC, ViZhe commented on vuepress-docs/docs/.vuepress/public/QSwitcher/default.html
> +      </div>
покажи на второй строчке эти состояния с model-value false

2022-04-28 21:04 UTC, ViZhe commented on vuepress-docs/docs/.vuepress/public/QSwitcher/disabled.html
> +        ></q-switch>
покажи рядом пример с false

2022-04-28 21:17 UTC, ViZhe commented on src/qComponents/QSwitch/src/q-switch.scss
> +      transform: translateX(calc(-100% + 22px));
```suggestion
      transform: translateX(calc(-90% + 20px));
```

2022-04-28 21:19 UTC, ViZhe commented on src/qComponents/QSwitch/src/q-switch.scss
> +        width: 22px;
```suggestion
      .q-switch__wrapper {
        transform: translateX(calc(-10% + 20px));
```

2022-04-28 21:19 UTC, ViZhe commented on src/qComponents/QSwitch/src/q-switch.scss
> +    width: 20px;
в переменную

2022-04-28 21:22 UTC, ViZhe commented on src/qComponents/QSwitch/src/q-switch.scss
> +    outline: none;
вот это какой кейс покрывает?

2022-04-28 21:25 UTC, ViZhe commented on src/qComponents/QSwitch/src/q-switch.scss
> +    }
люфтит
https://user-images.githubusercontent.com/8091902/165848398-2e5cf1b4-3518-45c3-afe4-f00ec8e9142d.mov

2022-04-28 21:29 UTC, ViZhe commented on src/qComponents/QSwitch/src/q-switch.scss
> +    width: 20px;
и тут кстати не 20 на самом то деле

2022-04-28 22:00 UTC, ViZhe commented on src/qComponents/QSwitch/src/q-switch.scss
> +      font-size: 12px;
тут не 12

2022-05-04 10:47 UTC, SeregaBB commented on src/qComponents/QSwitch/src/q-switch.scss
> +    outline: none;
&:focus - лишнее, убрал. 
второй селектор убирает outline в кейсе неактивным свитчем. 
клик по q-switch_disabled + space/enter - всё равно добавляет .focus-visible. вот этот кейс это и покрывает

2022-05-04 11:03 UTC, ViZhe requested changes

2022-05-04 11:35 UTC, ViZhe approved these changes

2022-05-05 07:31 UTC, Tim152 approved these changes

2022-05-05 07:36 UTC, merged