feat(QSlider): add tooltip, fix colors
Qvant-lab/qui-max pull request #289
Opened 2022-05-16 12:54 UTC by SeregaBB

2022-05-16 15:16 UTC, ViZhe commented on src/qComponents/QSlider/src/components/QSliderButton/QSliderButton.vue
> +      default: 'hover'
по дефолту без тултипа

2022-05-17 07:50 UTC, ViZhe commented on stories/components/QSlider/Range.ts
> +const data: QSliderPropData<number> = Array(100)
101

2022-05-17 07:50 UTC, ViZhe commented on stories/components/QSlider/Range.ts
> +    label: index === 0 || index === 99 ? String(index) : undefined
100

2022-05-17 07:51 UTC, ViZhe commented on stories/components/QSlider/Range.ts
> +      };
```suggestion
      return {        args,        value      };
```

2022-05-17 07:51 UTC, ViZhe commented on stories/components/QSlider/Range.ts
> +
это не совсем Range

2022-05-17 07:52 UTC, ViZhe commented on src/qComponents/QSlider/src/types.ts
> +export type QSliderTooltipMode = 'none' | 'hover' | 'always';
паттерн нейминга

2022-05-17 11:20 UTC, ViZhe commented on stories/components/QSlider/WithoutSteps.ts
> +      const value = ref<number>(0);
33

2022-05-17 11:21 UTC, ViZhe commented on stories/components/QSlider/WithoutSteps.ts
> +      const value = ref<number>(0);
и в другом примере выбери не первое значение

2022-05-17 11:27 UTC, ViZhe commented on src/qComponents/QSlider/src/QSlider.vue
> +    stepsHidden: {
showSteps

2022-05-17 11:52 UTC, ViZhe commented on src/qComponents/QSlider/src/types.ts
> +export type QSliderPropTooltipMode = 'none' | 'hover' | 'always';
вроде бы null достаточно вместо none

```suggestion
export type QSliderPropTooltipMode = Nullable<'hover' | 'always'>;
```

2022-05-17 13:37 UTC, ViZhe requested changes

2022-05-17 13:37 UTC, ViZhe commented on src/qComponents/QSlider/src/components/QSliderButton/q-slider-button.scss
> +    z-index: 99;
какое-то осознанное число?

2022-05-17 13:37 UTC, ViZhe commented on src/qComponents/QSlider/src/components/QSliderCaptions/QSliderCaptions.vue
> +                    }%`
стоит вынести за пределы h

2022-05-17 13:37 UTC, ViZhe commented on src/qComponents/QSlider/src/components/QSliderCaptions/QSliderCaptions.vue
> +              }%`
выглядит знакомо

2022-05-17 13:37 UTC, ViZhe commented on stories/components/QSlider/WithoutSteps.ts
> +      index === 0 || index === 100 || index === 12 || index === 33
[..].includes(index)

2022-05-18 10:00 UTC, ViZhe approved these changes

2022-05-18 13:55 UTC, Tim152 approved these changes

2022-05-18 13:55 UTC, merged