feat(QInputNumber): add prefix and suffix
Qvant-lab/qui-max pull request #290
Opened 2022-05-18 17:08 UTC by SeregaBB

2022-05-18 17:40 UTC, ViZhe commented on src/qComponents/QInputNumber/src/QInputNumber.vue
> +    });
уверен можно обойтись без двойной перезаписи input.value

2022-05-18 17:50 UTC, ViZhe requested changes

2022-05-18 17:50 UTC, ViZhe commented on src/qComponents/QInputNumber/src/QInputNumber.vue
> +    /** If input is not in focus value of the prefix will be displayed in input-number after main value */
стоит упростить и исправить копипасту

2022-05-18 21:31 UTC, SeregaBB commented on src/qComponents/QInputNumber/src/QInputNumber.vue
> +    });
+

2022-05-19 07:36 UTC, ViZhe commented on src/qComponents/QInputNumber/src/QInputNumber.vue
> +      return `${prefix} ${value} ${suffix}`.trim();
стоит перенести эту логику в formatNumber

2022-05-19 08:22 UTC, ViZhe approved these changes

2022-05-23 10:52 UTC, Tim152 approved these changes

2022-05-23 10:53 UTC, merged