fix(QFormItem): types
Qvant-lab/qui-max pull request #291
Opened 2022-05-20 09:28 UTC by shamilfrontend

2022-05-20 11:24 UTC, ViZhe requested changes

2022-05-20 11:24 UTC, ViZhe commented on src/qComponents/QFormItem/src/QFormItem.vue
> +      return props.for ?? props.prop;
кажется  тут происходит какое-то дублирование логики

2022-05-20 11:24 UTC, ViZhe commented on src/qComponents/QFormItem/src/types.ts
>  }
экспортни всё это из индекс файла

2022-05-20 12:13 UTC, shamilfrontend commented on src/qComponents/QFormItem/src/QFormItem.vue
> +      return props.for ?? props.prop;
переделал)

2022-05-20 15:07 UTC, ViZhe approved these changes

2022-05-23 10:53 UTC, Tim152 approved these changes

2022-05-23 10:54 UTC, merged