fix(QButton): colors, sizes, paddings
Qvant-lab/qui-max pull request #292
Opened 2022-05-20 12:15 UTC by SeregaBB

2022-05-20 13:02 UTC, ViZhe requested changes

2022-05-20 13:02 UTC, ViZhe commented on src/qComponents/QButton/src/q-button.scss
>        --background-color: transparent;
кажется можно дропнуть

2022-05-20 13:02 UTC, ViZhe commented on src/qComponents/QButton/src/q-button.scss
>      }
цвет тут и так уже задан,

2022-05-20 13:06 UTC, SeregaBB commented on src/qComponents/QButton/src/q-button.scss
> +    &:not(&.q-button_disabled) {
я добавил cursor: no-allowed на disabled. без этого правила, если вдруг случится, что у кнопки сразу два состояния loading и disabled, курсор не будет меняться на not-allowed

2022-05-20 13:26 UTC, SeregaBB commented on src/qComponents/QButton/src/q-button.scss
>      }
без этого правила будет вот так при двух состояниях (disabled + loading)
![image](https://user-images.githubusercontent.com/31646896/169536737-9d2a2614-c8ff-4bb3-9544-4bbc5db2e74a.png)

2022-05-23 10:51 UTC, ViZhe commented on src/qComponents/QButton/src/q-button.scss
> +    }
это относится только к q-button_theme_secondary

2022-05-23 11:02 UTC, ViZhe requested changes

2022-05-23 11:02 UTC, ViZhe commented on src/qComponents/QButton/src/q-button.scss
>        margin-left: 0;
вот это кажется лишнее?

2022-05-23 11:02 UTC, ViZhe commented on src/qComponents/QButton/src/q-button.scss
> +      box-shadow: none;
тут вероятно переменные

2022-05-23 15:01 UTC, ViZhe requested changes

2022-05-23 15:19 UTC, shamilfrontend commented on src/qComponents/QButton/src/q-button.scss
>    max-height: 40px;
тоже в переменную?

внизу вроде для модификатора `&_type_icon` задается аналогичная высота

2022-05-27 11:05 UTC, ViZhe requested changes

2022-06-20 15:27 UTC, Tim152 approved these changes

2022-06-20 15:28 UTC, merged