fix(QDatePicker): types
Qvant-lab/qui-max pull request #293
Opened 2022-05-23 10:11 UTC by shamilfrontend

2022-05-25 15:30 UTC, SeregaBB approved these changes

2022-05-25 15:34 UTC, skaflock commented on src/qComponents/QDatePicker/src/QDatePicker.vue
> +  QDatePickerPropStartPlaceholder,
Здесь точно должно быть столько одинаковых типов с разными названиями?

2022-05-26 13:34 UTC, skaflock approved these changes

2022-05-27 07:19 UTC, ViZhe commented on src/qComponents/QDatePicker/src/QDatePicker.vue
> +        :model-value="String(displayValue)"
приводить массив к строке таким образом не стоит

2022-05-27 07:28 UTC, ViZhe requested changes

2022-05-27 07:28 UTC, ViZhe commented on src/qComponents/QDatePicker/src/QDatePicker.vue
> +      !props.type ? false : props.type.includes('range')
налиш оператор?

2022-05-27 07:28 UTC, ViZhe commented on src/qComponents/QDatePicker/src/types.ts
> +export type QDatePickerPropDisabledValues = Nullable<{
межд у Prop пустые строки лучше дропнуть

2022-05-27 07:28 UTC, ViZhe commented on src/qComponents/QDatePicker/src/types.ts
> +  }[]
вынеси в отдельный тип и сделай его SomeType[]

2022-05-27 07:28 UTC, ViZhe commented on src/qComponents/QDatePicker/src/types.ts
> +    { hidePicker }?: { hidePicker?: boolean }
`options?: { hidePicker?: boolean }`

2022-06-09 14:54 UTC, shamilfrontend commented on src/qComponents/QDatePicker/src/QDatePicker.vue
> +        :model-value="String(displayValue)"
поправил

2022-06-09 20:14 UTC, ViZhe requested changes

2022-06-09 20:14 UTC, ViZhe commented on src/qComponents/QDatePicker/src/QDatePicker.vue
> +      v-if="!isRanged && typeof displayValue === 'string'"
скорее всего тут стоит разделить компутед displayValue на два, для isRanged и для не isRanged

2022-06-23 09:25 UTC, ViZhe requested changes

2022-06-23 09:25 UTC, ViZhe commented on src/qComponents/QDatePicker/src/QDatePicker.vue
> +      v-if="isRanged && Array.isArray(rangeDisplayValue)"
Array.isArray(rangeDisplayValue) лишняя проверка
из rangeDisplayValue стоит всегда массив возвращать

2022-06-23 09:25 UTC, ViZhe commented on src/qComponents/QDatePicker/src/QDatePicker.vue
> +        return null;
фигурные скобки если не помещается на одной строке

2022-06-23 09:55 UTC, raha-frontend commented on src/qComponents/QDatePicker/src/types.ts
> +  displayValue: ComputedRef<Nullable<Enumerable<string>>>;
судя по computed-свойтву displayValue, тут только string

2022-06-23 10:08 UTC, shamilfrontend commented on src/qComponents/QDatePicker/src/types.ts
> +  displayValue: ComputedRef<Nullable<Enumerable<string>>>;
Поправил, Спасибо)))

2022-06-23 10:15 UTC, ViZhe approved these changes

2022-06-27 11:48 UTC, merged