feat(QCheckbox): checkbox redesign
Qvant-lab/qui-max pull request #306
Opened 2022-06-17 09:17 UTC by VasiliyRusin

2022-06-17 09:27 UTC, shamilfrontend commented on src/qComponents/QCheckbox/src/QCheckbox.vue
> +import { computed, defineComponent, inject, watch, ref, PropType } from 'vue';
`import type { PropType } from 'vue';`

2022-06-17 09:51 UTC, shamilfrontend approved these changes

2022-06-22 07:58 UTC, shamilfrontend commented on vuepress-docs/docs/.vuepress/public/QCheckbox/labelSize.html
> +        const model = ref(true);
value?

2022-06-22 08:09 UTC, SeregaBB commented on vuepress-docs/docs/components/QCheckbox.md
> +- default `regular`
```suggestion
- Type: `String`
- Default: `regular`
```

и везде в qcheckbox можно тож привести к такому виду :)

2022-06-22 08:15 UTC, SeregaBB commented on vuepress-docs/docs/.vuepress/public/QCheckbox/QCheckbox.html
> +          labelSize="small"
```suggestion
          label-size="small"
```

2022-06-22 08:16 UTC, SeregaBB commented on vuepress-docs/docs/.vuepress/public/QCheckbox/labelSize.html
> +        labelSize="small"
```suggestion
        label-size="small"
```

2022-06-23 06:42 UTC, SeregaBB requested changes

2022-06-23 06:42 UTC, SeregaBB commented on src/qComponents/QCheckbox/src/QCheckbox.vue
> +    );
```suggestion
    const isIntermediate = computed<boolean>(
      () => !isChecked.value && Boolean(props.indeterminate)
    );
```

2022-06-23 07:08 UTC, SeregaBB approved these changes

2022-06-23 07:14 UTC, shamilfrontend commented on src/qComponents/QCheckbox/src/QCheckbox.vue
>        :tabindex="indeterminate ? 0 : false"
сделай плиз проверку типов) по моему тут boolean нельзя ставить)

`rm -rf node_modules && yarn cache clean && yarn`
`rm -rf node_modules/@types/react`
`npx vue-tsc --noEmit --skipLibCheck`

2022-06-23 07:17 UTC, shamilfrontend commented on src/qComponents/QCheckbox/src/QCheckbox.vue
>        :tabindex="indeterminate ? 0 : false"
скорее всего нужно вместо `false` прописать `undefined`

2022-06-23 10:11 UTC, ViZhe requested changes

2022-06-23 10:11 UTC, ViZhe commented on stories/components/QCheckbox.stories.ts
> +        :labelSize="args.labelSize"
кебаб

2022-06-23 10:19 UTC, ViZhe approved these changes

2022-07-12 09:19 UTC, Tim152 approved these changes

2022-07-12 09:23 UTC, merged