feat(QRadio): radio button redesign
Qvant-lab/qui-max pull request #309
Opened 2022-06-22 06:27 UTC by VasiliyRusin

2022-06-22 07:11 UTC, shamilfrontend commented on src/qComponents/QRadio/src/types.ts
>    disabled: Nullable<boolean>;
Создай под каждый пропс тип и экспортируй их отсюда

далее в компоненте через `as PropType` примени эти типы

2022-06-22 07:11 UTC, shamilfrontend commented on src/qComponents/QRadio/src/types.ts
>    disabled: Nullable<boolean>;
Также все типы пропсов добавь к общему экспорту из компонента

вот сюда
https://github.com/Qvant-lab/qui-max/blob/main/src/qComponents/QRadio/index.ts#L7

2022-06-22 07:29 UTC, shamilfrontend commented on stories/components/QRadio.stories.ts
> +          :labelSize="args.labelSize"
Поставь `labelSize` чтоб было выше события)

2022-06-22 07:48 UTC, SeregaBB requested changes

2022-06-22 07:48 UTC, SeregaBB commented on src/qComponents/QRadio/src/q-radio.scss
> +    color: var(--checkbox-label-color);
наверное, стоит завести отдельную переменную для радио

2022-06-22 08:18 UTC, SeregaBB commented on vuepress-docs/docs/.vuepress/public/QRadio/labelSize.html
> +          labelSize="small"
```suggestion
          label-size="small"
```

2022-06-22 08:19 UTC, SeregaBB commented on vuepress-docs/docs/.vuepress/public/QRadio/main.html
> +              labelSize="small"
```suggestion
              label-size="small"
```

2022-06-23 06:39 UTC, shamilfrontend commented on stories/components/QRadio.stories.ts
> +          :labelSize="args.labelSize"
тут вроде еще не поправлено)

2022-06-23 07:08 UTC, SeregaBB approved these changes

2022-06-23 07:45 UTC, shamilfrontend approved these changes

2022-06-23 09:21 UTC, ViZhe approved these changes

2022-06-27 11:23 UTC, Tim152 commented on src/qComponents/QRadio/src/QRadio.vue
> +      validator: validateArray<QRadioPropLabelSize>(['regular', 'small'])
лучше использовать `medium` для консистентности вместо `regular` по аналогии с др компонентами (QButton)

2022-06-27 11:35 UTC, Tim152 approved these changes

2022-06-27 11:35 UTC, merged