[QInputNumber] upgrade with additions and formatting
Qvant-lab/qui-max pull request #74
Opened 2021-06-16 13:50 UTC by Esvalirion

2021-06-28 08:40 UTC, ViZhe requested changes

2021-06-28 08:40 UTC, ViZhe commented on src/qComponents/QInputNumber/src/QInputNumber.vue
> +      @click.prevent="handleChangeNumberButtonClick(false)"
?

2021-06-28 08:40 UTC, ViZhe commented on src/qComponents/QInputNumber/src/QInputNumber.vue
> +        : 0;
?

2021-06-28 08:40 UTC, ViZhe commented on src/qComponents/QInputNumber/src/QInputNumber.vue
> +      return getValueWithoutAdditions(formattedValue.value, additions.value);
сокращенная запись

2021-06-28 08:40 UTC, ViZhe commented on src/qComponents/QInputNumber/src/QInputNumber.vue
> +    const inputRef = ref<QInputInstance | null>(null);
тип рефки на компонент имеют немного другой вид, погляди как в других местах

2021-06-28 08:40 UTC, ViZhe commented on src/qComponents/QInputNumber/src/QInputNumber.vue
> +import type { QInputInstance } from '@/qComponents/QInput/src/types';
/src/types лишнее

2021-06-28 08:40 UTC, ViZhe commented on src/qComponents/QInputNumber/src/QInputNumber.vue
> +            (event.key === 'ArrowRight' &&
дублируется с case тогда уж лучше раделить на отдельные case

2021-07-02 09:16 UTC, ViZhe commented on src/qComponents/QInputNumber/src/QInputNumber.vue
> +      @click="handleChangeNumberButtonClick(false)"
подобная запись плохо читается, лучше сделай 2 обработчика которые вызывают одну функцию с разными аргументами

2021-07-02 09:16 UTC, ViZhe commented on src/qComponents/QInputNumber/src/QInputNumber.vue
> +  UPDATE_MODEL_VALUE_EVENT
это законфликтит когда Тимми доделает, с константами плохо дружит сторибук, поэтому лучше передалть на строки

2021-07-14 09:25 UTC, ViZhe requested changes

2021-07-14 09:25 UTC, ViZhe commented on .husky/_/husky.sh
> +#!/bin/sh
?

2021-07-14 09:25 UTC, ViZhe commented on src/qComponents/QInputNumber/src/QInputNumber.vue
> +
лишний перенос

2021-07-16 08:15 UTC, Esvalirion commented on .husky/_/husky.sh
> +#!/bin/sh
![image](https://user-images.githubusercontent.com/1199337/125915705-d249ecdd-6e2e-4390-b258-a4dc7326b3c4.png)

2021-10-18 13:53 UTC, merged